/**
 * Identity codegen (S1b.1): every registered artwork file → a react-native-svg component and a web component.
 *
 *   pnpm --filter @senryo/identity codegen                    # verify hashes, regenerate src/generated/**
 *   pnpm --filter @senryo/identity codegen --rehash           # also re-pin sha256 of changed Senryo originals
 *   pnpm --filter @senryo/identity codegen --emit-svg <dir>   # also write the optimised SVGs for render review
 *   pnpm --filter @senryo/identity codegen --derive           # first (re)write every derived variant from its source
 *
 * 1. Each file's sha256 must equal the registry's. A changed first-party file is an error and is never re-pinned. A
 *    derived variant (`ArtFile.derived`) must equal `deriveSvg(source)` byte for byte; `--derive` writes it and prints
 *    its sha256 for the record.
 * 2. SVG → SVGO + guard + SVGR per platform (./svg-pipeline.ts); PNG (owner ships raster only) → an image component.
 * 3. `src/generated/{native,web}/index.ts` map key → variant → component; `manifest.json` pins what was generated, so
 *    the invariant `identity-provenance` catches a registry change that wasn't regenerated.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ART_SOURCES } from "../src/art/index.ts";
import { deriveSvg } from "../src/derive.ts";
import type { ArtFile, ArtSource, MarkVariant } from "../src/types.ts";
import { optimise, type Platform, rasterComponent, svgComponent } from "./svg-pipeline.ts";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = resolve(PKG, "../..");
const ART_DIR = join(PKG, "src/art");
const OUT = join(PKG, "src/generated");
const PLATFORMS: readonly Platform[] = ["native", "web"];
const REHASH = process.argv.includes("--rehash");
const DERIVE = process.argv.includes("--derive");
const EMIT = process.argv.includes("--emit-svg") ? process.argv[process.argv.indexOf("--emit-svg") + 1] : undefined;
const HEADER = "// GENERATED by packages/identity/scripts/codegen.ts — do not edit; change the source file and re-run.";

const sha256 = (bytes: Buffer): string => createHash("sha256").update(bytes).digest("hex");
const pascal = (s: string): string =>
  s
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");

/** Pins the new hash of a re-rendered Senryo original in whichever src/art file records the old one. */
function rehash(oldHash: string, newHash: string): void {
  for (const name of readdirSync(ART_DIR)) {
    const path = join(ART_DIR, name);
    const text = readFileSync(path, "utf8");
    if (text.includes(oldHash)) writeFileSync(path, text.replace(oldHash, newHash));
  }
}

function verify(source: ArtSource, variant: string, file: ArtFile, bytes: Buffer): void {
  const actual = sha256(bytes);
  // A variant just (re)written by `--derive` has its new hash printed for the record; the invariant holds it to that.
  const fresh = DERIVE && file.derived !== undefined;
  if (actual !== file.sha256 && !fresh) {
    if (!(REHASH && source.provenance === "senryo-original")) {
      throw new Error(`${source.key}/${variant}: ${file.path} sha256 ${actual} ≠ registry ${file.sha256}`);
    }
    rehash(file.sha256, actual);
    console.log(`re-pinned ${file.path} → ${actual}`);
  }
  if (!file.path.endsWith(".svg")) return;
  const declared = /<svg[^>]*\sviewBox="([^"]+)"/.exec(bytes.toString("utf8"))?.[1];
  const viewBox = declared
    ?.trim()
    .split(/[\s,]+/)
    .join(" ");
  if (viewBox !== undefined && viewBox !== file.viewBox) {
    throw new Error(`${source.key}/${variant}: viewBox "${viewBox}" ≠ registry "${file.viewBox}"`);
  }
}

/** A derived variant is reproducible: (re)written with `--derive`, otherwise checked against its source. */
function derive(source: ArtSource, variant: string, file: ArtFile): void {
  if (!file.derived) return;
  const expected = deriveSvg(readFileSync(join(ROOT, file.derived.from), "utf8"), file.derived);
  const abs = join(ROOT, file.path);
  if (DERIVE) {
    writeFileSync(abs, expected);
    console.log(`derived ${file.path} → ${sha256(Buffer.from(expected))}`);
  } else if (!existsSync(abs) || readFileSync(abs, "utf8") !== expected) {
    throw new Error(`${source.key}/${variant}: ${file.path} ≠ deriveSvg(${file.derived.from}) — run codegen --derive`);
  }
}

interface Generated {
  key: string;
  variant: MarkVariant;
  stem: string;
  component: string;
}

async function componentFor(file: ArtFile, bytes: Buffer, stem: string, component: string, platform: Platform) {
  if (!file.path.endsWith(".svg")) {
    const asset = relative(join(OUT, platform), join(ROOT, file.path)).split("\\").join("/");
    return rasterComponent(component, asset, platform);
  }
  const svg = optimise(bytes.toString("utf8"), file.path, stem, platform);
  if (EMIT && platform === "web") writeFileSync(join(resolve(EMIT), `${stem}.svg`), svg);
  return svgComponent(svg, component, platform);
}

async function generate(): Promise<void> {
  rmSync(OUT, { recursive: true, force: true });
  if (EMIT) mkdirSync(resolve(EMIT), { recursive: true });
  for (const platform of PLATFORMS) mkdirSync(join(OUT, platform), { recursive: true });
  const made: Generated[] = [];
  const manifest: Record<string, string> = {};
  for (const source of ART_SOURCES) {
    for (const [variant, file] of Object.entries(source.variants) as [MarkVariant, ArtFile][]) {
      derive(source, variant, file);
      const bytes = readFileSync(join(ROOT, file.path));
      verify(source, variant, file, bytes);
      const stem = `${source.key}-${variant.toLowerCase()}`;
      const component = `Art${pascal(`${source.key}-${variant}`)}`;
      const note = `${HEADER}\n// Source: ${file.path} (sha256 ${sha256(bytes)}) · ${source.owner} · ${source.pageUrl}\n`;
      for (const platform of PLATFORMS) {
        const code = await componentFor(file, bytes, stem, component, platform);
        writeFileSync(join(OUT, platform, `${stem}.tsx`), note + code);
      }
      made.push({ key: source.key, variant, stem, component });
      manifest[`${source.key}/${variant}`] = sha256(bytes);
    }
  }
  writeIndex("native", made, 'import type { SvgProps } from "react-native-svg";', "SvgProps");
  writeIndex("web", made, 'import type { SVGProps } from "react";', "SVGProps<SVGSVGElement>");
  writeFileSync(join(OUT, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(`generated ${made.length} marks × ${PLATFORMS.length} platforms`);
}

function writeIndex(platform: Platform, made: Generated[], propsImport: string, propsType: string): void {
  const byKey = new Map<string, Generated[]>();
  for (const g of made) byKey.set(g.key, [...(byKey.get(g.key) ?? []), g]);
  const lines = [
    HEADER,
    'import type { ComponentType } from "react";',
    propsImport,
    'import type { MarkVariant } from "../../types.ts";',
    ...made.map((g) => `import ${g.component} from "./${g.stem}.tsx";`),
    "",
    `export type ArtComponent = ComponentType<${propsType}>;`,
    "",
    "export const ART_COMPONENTS: Readonly<Record<string, Partial<Record<MarkVariant, ArtComponent>>>> = {",
    ...[...byKey].map(
      ([key, gs]) => `  ${JSON.stringify(key)}: { ${gs.map((g) => `${g.variant}: ${g.component}`).join(", ")} },`,
    ),
    "};",
    "",
  ];
  writeFileSync(join(OUT, platform, "index.ts"), lines.join("\n"));
}

await generate();
