/**
 * Fetches every catalogued mark (./catalog.ts) from its public source and pins it.
 *
 *   pnpm --filter @senryo/identity run fetch      # download → sources/<key>/, write src/art/generated/fetched.ts
 *   pnpm --filter @senryo/identity codegen    # then regenerate the components
 *
 * Each file is stored byte-for-byte as served, with its URL and sha256 in the generated record. Upstreams are pinned
 * (web3icons, Material Symbols and Monad's token list by commit, Simple Icons by version, a Commons file by its
 * version's SHA-1), so a re-run only changes a record when the catalog or a pin changes; `retrieved` moves only for a
 * record whose bytes changed. Derived colourways (the dark-ink silhouette, a brand-hex fill) are written with
 * `deriveSvg`, the same function codegen and the `identity-provenance` invariant re-run. Shared helpers live in
 * ./fetch-lib.ts; Wikimedia Commons in ./fetch-commons.ts.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { MONAD_TOKEN_LIST } from "@senryo/config";
import { MATERIAL_COMMIT } from "../src/art/auth.ts";
import { deriveSvg } from "../src/derive.ts";
import type { ArtFile, ArtSource, Derivation, MarkVariant } from "../src/types.ts";
import { CATALOG, type CatalogEntry, type FetchSpec } from "./catalog.ts";
import { fromCommons } from "./fetch-commons.ts";
import {
  DARK_INK,
  type Fetched,
  fetched,
  get,
  getSvg,
  LIGHT_INK,
  type Piece,
  type Presentation,
  pathOf,
  soleInk,
  surfaceFor,
} from "./fetch-lib.ts";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = resolve(PKG, "../..");
const OUT = join(PKG, "src/art/generated/fetched.ts");
const HEADER =
  "// GENERATED by packages/identity/scripts/fetch-marks.ts from scripts/catalog.ts — do not edit; change the catalog and re-run.";

const WEB3ICONS_COMMIT = "ad3cbe05229db54931cd8b2c2a86662288a0ce50";
const WEB3ICONS_REPO = "https://github.com/0xa3k5/web3icons";
const WEB3ICONS_RAW = `https://raw.githubusercontent.com/0xa3k5/web3icons/${WEB3ICONS_COMMIT}/raw-svgs`;
const WEB3ICONS_LICENCE_URL = `${WEB3ICONS_REPO}/blob/${WEB3ICONS_COMMIT}/LICENCE`;
/** The library draws every mark on a 24-unit grid with 3 units of clear space: 3/24 of the edge. */
const WEB3ICONS_INSET_PERMILLE = 125;
const SIMPLE_ICONS_VERSION = "16.33.0";
const SIMPLE_ICONS_CDN = `https://cdn.jsdelivr.net/npm/simple-icons@${SIMPLE_ICONS_VERSION}`;
const SIMPLE_ICONS_LICENCE_URL = `https://github.com/simple-icons/simple-icons/blob/${SIMPLE_ICONS_VERSION}/LICENSE.md`;
const HYPERLIQUID_APP = "https://app.hyperliquid.xyz";
const MATERIAL_RAW = `https://raw.githubusercontent.com/google/material-design-icons/${MATERIAL_COMMIT}`;
const MATERIAL_LICENCE_URL = `https://github.com/google/material-design-icons/blob/${MATERIAL_COMMIT}/LICENSE`;
/** Material's system-icon grid: 24 units with a 20-unit live area, so 2/24 of the edge is clear space. */
const MATERIAL_INSET_PERMILLE = 83;

const ISO_DATE_CHARS = 10;
const PNG_SIGNATURE = Buffer.from("89504e470d0a1a0a", "hex");
/** A commit named in a licence line: its first 8 hex digits. */
const SHORT_SHA_CHARS = 8;
/** IHDR is the first chunk: width and height (big-endian u32) sit right after its length and type. */
const PNG_WIDTH_OFFSET = 16;
const PNG_HEIGHT_OFFSET = 20;

const sha256 = (bytes: string | Buffer): string => createHash("sha256").update(bytes).digest("hex");

/** A raster file must really be a PNG; its viewBox is its pixel size (IHDR width × height). */
async function getPng(url: string): Promise<Buffer> {
  const bytes = Buffer.from(await (await fetched(url)).arrayBuffer());
  if (!bytes.subarray(0, PNG_SIGNATURE.length).equals(PNG_SIGNATURE)) throw new Error(`${url}: not a PNG`);
  return bytes;
}

function pngViewBox(png: Buffer): string {
  return `0 0 ${png.readUInt32BE(PNG_WIDTH_OFFSET)} ${png.readUInt32BE(PNG_HEIGHT_OFFSET)}`;
}

function viewBoxOf(svg: string, label: string): string {
  const declared = /<svg[^>]*\sviewBox="([^"]+)"/.exec(svg)?.[1];
  if (!declared) throw new Error(`${label}: no viewBox`);
  return declared
    .trim()
    .split(/[\s,]+/)
    .join(" ");
}

async function fromWeb3Icons(key: string, spec: Extract<FetchSpec, { from: "web3icons" }>): Promise<Fetched> {
  const url = (variant: string) => `${WEB3ICONS_RAW}/${spec.group}/${variant}/${spec.name}.svg`;
  const name = (variant: string, suffix = "") => `web3icons-${spec.group}-${variant}-${spec.name}${suffix}.svg`;
  const pieces: Piece[] = [];
  for (const take of spec.take) {
    if (take === "disc") {
      const present: Presentation = { insetPermille: 0, surface: "any", shape: "disc", crop: "disc" };
      pieces.push({
        variant: "disc",
        name: name("background"),
        url: url("background"),
        body: await getSvg(url("background")),
        present,
      });
    } else if (take === "symbol") {
      const present: Presentation = { insetPermille: WEB3ICONS_INSET_PERMILLE, surface: "any", shape: "free" };
      pieces.push({
        variant: "symbol",
        name: name("branded"),
        url: url("branded"),
        body: await getSvg(url("branded")),
        present,
      });
    } else {
      const light = await getSvg(url("mono"));
      const derived: Derivation = {
        from: pathOf(key, name("mono")),
        recolour: { [soleInk(light, url("mono"))]: DARK_INK },
        basis: `MIT License (${WEB3ICONS_LICENCE_URL}): "the rights to use, copy, modify, merge, publish, distribute" — the library's one-ink silhouette, recoloured to dark ink for light grounds.`,
      };
      const base = { insetPermille: WEB3ICONS_INSET_PERMILLE, shape: "free" } as const;
      pieces.push({
        variant: "monoLight",
        name: name("mono"),
        url: url("mono"),
        body: light,
        present: { ...base, surface: "dark" },
      });
      pieces.push({
        variant: "monoDark",
        name: name("mono", "-dark"),
        url: url("mono"),
        body: deriveSvg(light, derived),
        present: { ...base, surface: "light" },
        derived,
      });
    }
  }
  return {
    provenance: "open-library",
    pageUrl: `${WEB3ICONS_REPO}/tree/${WEB3ICONS_COMMIT}/raw-svgs/${spec.group}`,
    licence: `MIT License, "Copyright (c) 2024 0xa3k5" (${WEB3ICONS_LICENCE_URL}): "Permission is hereby granted, free of charge … to use, copy, modify, merge, publish, distribute". The licence covers the icon files; the mark itself stays its owner's trademark and is used nominatively, only to identify the asset, network or venue it belongs to.`,
    usage:
      "Drawn on the library's 24-unit grid (3 units of clear space). The disc is the library's brand-colour background variant clipped to its inscribed circle by codegen; the dark-ink silhouette is the white one recoloured.",
    pieces,
  };
}

async function fromHyperliquid(spec: Extract<FetchSpec, { from: "hyperliquid" }>): Promise<Fetched> {
  const url = `${HYPERLIQUID_APP}/coins/${spec.coin}.svg`;
  const present: Presentation = { insetPermille: 0, surface: "any", shape: "disc" };
  return {
    provenance: "venue-metadata",
    pageUrl: `${HYPERLIQUID_APP}/trade/${spec.coin}`,
    licence: `No separate licence: this is the icon Hyperliquid's own app serves for the ${spec.coin} market it lists (${url}), i.e. venue-published instrument metadata. The mark belongs to its project and is used nominatively, only to identify that asset beside its ticker.`,
    usage: "A full disc as served; shown only for the asset itself, never as a venue badge.",
    pieces: [{ variant: "disc", name: `hyperliquid-coin-${spec.coin}.svg`, url, body: await getSvg(url), present }],
  };
}

interface SimpleIcon {
  title: string;
  slug?: string;
  hex: string;
}

let simpleIconsData: Promise<SimpleIcon[]> | undefined;
function simpleIcon(slug: string): Promise<SimpleIcon> {
  simpleIconsData ??= get(`${SIMPLE_ICONS_CDN}/data/simple-icons.json`).then(
    (text) => JSON.parse(text) as SimpleIcon[],
  );
  return simpleIconsData.then((icons) => {
    const found = icons.find((i) => (i.slug ?? i.title.toLowerCase().replace(/[^a-z0-9]/g, "")) === slug);
    if (!found) throw new Error(`simple-icons: no data entry for "${slug}"`);
    return found;
  });
}

async function fromSimpleIcons(key: string, spec: Extract<FetchSpec, { from: "simple-icons" }>): Promise<Fetched> {
  const url = `${SIMPLE_ICONS_CDN}/icons/${spec.slug}.svg`;
  const [delivered, icon] = await Promise.all([getSvg(url), simpleIcon(spec.slug)]);
  const name = (suffix = "") => `simple-icons-${spec.slug}${suffix}.svg`;
  const base = { insetPermille: 0, shape: "free" } as const;
  const fill = (rootFill: string): Derivation => ({
    from: pathOf(key, name()),
    recolour: {},
    rootFill,
    basis: `CC0 1.0 Universal (${SIMPLE_ICONS_LICENCE_URL}) dedicates the icon file to the public domain; the library itself serves each icon in a chosen colour (https://cdn.simpleicons.org/[SLUG]/[COLOR]).`,
  });
  const brand = fill(`#${icon.hex}`);
  const light = fill(LIGHT_INK);
  return {
    provenance: "open-library",
    pageUrl: `https://simpleicons.org/?q=${spec.slug}`,
    licence: `CC0 1.0 Universal (${SIMPLE_ICONS_LICENCE_URL}) for the icon file. The library's DISCLAIMER.md: the brand stays its owner's trademark; used nominatively, to identify the underlying company of an instrument, never as an endorsement. Brand colour #${icon.hex} is the value in the library's data file.`,
    usage: `Always beside the instrument's ticker and type (study 08: company artwork never drops the perp / tokenized distinction). The colour mark is the one-path icon filled with #${icon.hex}.`,
    pieces: [
      { variant: "monoDark", name: name(), url, body: delivered, present: { ...base, surface: "light" } },
      {
        variant: "symbol",
        name: name("-brand"),
        url,
        body: deriveSvg(delivered, brand),
        // A black brand (SpaceX) reads as `light`: on dark grounds it gets a light plate, beside its light silhouette.
        present: { ...base, surface: surfaceFor(icon.hex) },
        derived: brand,
      },
      {
        variant: "monoLight",
        name: name("-light"),
        url,
        body: deriveSvg(delivered, light),
        present: { ...base, surface: "dark" },
        derived: light,
      },
    ],
  };
}

/**
 * A neutral glyph from Google's Material Symbols at the pinned commit, for an instrument no owner's mark identifies
 * (crude oil). It has no fill of its own (the implicit black): the delivered file is the dark-ink symbol, and the
 * light silhouette is it with a white root fill. The Apache-2.0 text is written beside the files (§4a).
 */
async function fromMaterialSymbols(
  key: string,
  spec: Extract<FetchSpec, { from: "material-symbols" }>,
): Promise<Fetched> {
  const file = `${spec.name}${spec.filled ? "_fill1" : ""}_24px.svg`;
  const url = `${MATERIAL_RAW}/symbols/web/${spec.name}/materialsymbols${spec.style}/${file}`;
  const delivered = await getSvg(url);
  const name = (suffix = "") =>
    `material-symbols-${spec.style}-${file.replace(/_/g, "-").replace(/\.svg$/, "")}${suffix}.svg`;
  const light: Derivation = {
    from: pathOf(key, name()),
    recolour: {},
    rootFill: LIGHT_INK,
    basis: `Apache License 2.0 (${MATERIAL_LICENCE_URL}) §2: "a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display … and distribute the Work" — the one-ink glyph filled white for dark grounds.`,
  };
  const base = { insetPermille: MATERIAL_INSET_PERMILLE, shape: "free" } as const;
  const licenceRaw = `${MATERIAL_RAW}/LICENSE`;
  return {
    provenance: "open-library",
    pageUrl: `https://fonts.google.com/icons?selected=Material+Symbols+${spec.style[0]?.toUpperCase()}${spec.style.slice(1)}:${spec.name}`,
    licence: `Apache License 2.0 (${MATERIAL_LICENCE_URL}), google/material-design-icons at commit ${MATERIAL_COMMIT.slice(0, SHORT_SHA_CHARS)}. README: "We have made these icons available for you to incorporate into your products under the Apache License Version 2.0 … Feel free to remix and re-share these icons and documentation in your products." The licence text ships beside the files (LICENSE-material-design-icons.txt, §4a); credited in About & sources.`,
    usage:
      "A neutral glyph for an instrument with no owner's mark — never an issuer's or a venue's logo, always beside its ticker and type.",
    pieces: [
      { variant: "symbol", name: name(), url, body: delivered, present: { ...base, surface: "light" } },
      {
        variant: "monoLight",
        name: name("-light"),
        url,
        body: deriveSvg(delivered, light),
        present: { ...base, surface: "dark" },
        derived: light,
      },
    ],
    notices: [{ name: "LICENSE-material-design-icons.txt", url: licenceRaw, body: await get(licenceRaw) }],
  };
}

/**
 * A J11 spot token's logo from Monad's token list at the pinned commit — the file its issuer submitted (SVG or PNG),
 * kept as delivered. Token art is a full disc (checked by rendering the listed logos, 1 Oct 2026).
 */
async function fromMonadTokenList(spec: Extract<FetchSpec, { from: "monad-token-list" }>): Promise<Fetched> {
  const folder = `mainnet/${encodeURIComponent(spec.dir)}`;
  const url = `${MONAD_TOKEN_LIST.raw}/${MONAD_TOKEN_LIST.commit}/${folder}/${spec.file}`;
  const present: Presentation = { insetPermille: 0, surface: "any", shape: "disc" };
  const body = spec.file.endsWith(".png") ? await getPng(url) : await getSvg(url);
  const ext = spec.file.slice(spec.file.lastIndexOf("."));
  return {
    provenance: "first-party",
    pageUrl: `${MONAD_TOKEN_LIST.repo}/tree/${MONAD_TOKEN_LIST.commit}/${folder}`,
    licence: `monad-crypto/token-list (Monad's official token list), ${folder}/${spec.file} at commit ${MONAD_TOKEN_LIST.commit.slice(0, SHORT_SHA_CHARS)}: the logo the issuer submitted with its token (CONTRIBUTING.md: "must provide a logo in SVG or PNG format"). The repo has no LICENSE and says inclusion "does not imply endorsement". ${spec.symbol} is its issuer's mark, used nominatively beside its ticker.`,
    usage:
      "Token art beside the ticker in token rows, the token page and the ticket; never as a venue or network badge.",
    pieces: [{ variant: "disc", name: `${spec.dir.toLowerCase()}-token-monad-tokenlist${ext}`, url, body, present }],
  };
}

function fetchEntry(entry: CatalogEntry): Promise<Fetched> {
  const { spec } = entry;
  if (spec.from === "web3icons") return fromWeb3Icons(entry.key, spec);
  if (spec.from === "hyperliquid") return fromHyperliquid(spec);
  if (spec.from === "monad-token-list") return fromMonadTokenList(spec);
  if (spec.from === "wikimedia-commons") return fromCommons(entry.key, spec);
  if (spec.from === "material-symbols") return fromMaterialSymbols(entry.key, spec);
  return fromSimpleIcons(entry.key, spec);
}

function toRecord(entry: CatalogEntry, fetched: Fetched, previous: ArtSource | undefined, today: string): ArtSource {
  const variants: Partial<Record<MarkVariant, ArtFile>> = {};
  for (const piece of fetched.pieces) {
    const path = pathOf(entry.key, piece.name);
    mkdirSync(dirname(join(ROOT, path)), { recursive: true });
    writeFileSync(join(ROOT, path), piece.body);
    variants[piece.variant] = {
      path,
      url: piece.url,
      sha256: sha256(piece.body),
      viewBox: typeof piece.body === "string" ? viewBoxOf(piece.body, piece.url) : pngViewBox(piece.body),
      ...piece.present,
      ...(piece.derived ? { derived: piece.derived } : {}),
    };
  }
  for (const notice of fetched.notices ?? []) writeFileSync(join(ROOT, pathOf(entry.key, notice.name)), notice.body);
  const unchanged =
    previous !== undefined &&
    JSON.stringify(Object.values(previous.variants).map((f) => f.sha256)) ===
      JSON.stringify(Object.values(variants).map((f) => f.sha256));
  return {
    key: entry.key,
    owner: entry.owner,
    provenance: fetched.provenance,
    pageUrl: fetched.pageUrl,
    licence: fetched.licence,
    retrieved: unchanged ? previous.retrieved : today,
    usage: fetched.usage,
    variants,
  };
}

async function main(): Promise<void> {
  const previous: readonly ArtSource[] = existsSync(OUT) ? (await import(pathToFileURL(OUT).href)).FETCHED_ART : [];
  const today = new Date().toISOString().slice(0, ISO_DATE_CHARS);
  const records: ArtSource[] = [];
  for (const entry of CATALOG) {
    const fetched = await fetchEntry(entry);
    const record = toRecord(
      entry,
      fetched,
      previous.find((p) => p.key === entry.key),
      today,
    );
    records.push(record);
    console.log(`${entry.key} ← ${entry.spec.from}: ${Object.keys(record.variants).join(", ")}`);
  }
  mkdirSync(dirname(OUT), { recursive: true });
  const body = `export const FETCHED_ART: readonly ArtSource[] = ${JSON.stringify(records, null, 2)};\n`;
  writeFileSync(OUT, `${HEADER}\nimport type { ArtSource } from "../../types.ts";\n\n${body}`);
  console.log(`fetched ${records.length} marks → ${OUT.slice(ROOT.length + 1)} — now run codegen`);
}

await main();
