/**
 * Fetches every catalogued mark (./catalog.ts) from its public source and pins it.
 *
 *   pnpm --filter @senryo/identity fetch      # download → sources/<key>/, write src/art/generated/fetched.ts
 *   pnpm --filter @senryo/identity codegen    # then regenerate the components
 *
 * Each file is stored byte-for-byte as served, with its URL and sha256 in the generated record. Upstreams are pinned
 * (web3icons by commit, Simple Icons by version), so a re-run only changes a record when the catalog or a pin changes;
 * `retrieved` moves only for a record whose bytes changed. Derived colourways (the dark-ink silhouette, a brand-hex
 * fill) are written with `deriveSvg`, the same function codegen and the `identity-provenance` invariant re-run.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { deriveSvg } from "../src/derive.ts";
import type { ArtFile, ArtSource, Derivation, MarkVariant, Provenance } from "../src/types.ts";
import { CATALOG, type CatalogEntry, type FetchSpec } from "./catalog.ts";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = resolve(PKG, "../..");
const SOURCES = "packages/identity/sources";
const OUT = join(PKG, "src/art/generated/fetched.ts");
const HEADER =
  "// GENERATED by packages/identity/scripts/fetch-marks.ts from scripts/catalog.ts — do not edit; change the catalog and re-run.";

const WEB3ICONS_COMMIT = "ad3cbe05229db54931cd8b2c2a86662288a0ce50";
const WEB3ICONS_REPO = "https://github.com/0xa3k5/web3icons";
const WEB3ICONS_RAW = `https://raw.githubusercontent.com/0xa3k5/web3icons/${WEB3ICONS_COMMIT}/raw-svgs`;
const WEB3ICONS_LICENCE_URL = `${WEB3ICONS_REPO}/blob/${WEB3ICONS_COMMIT}/LICENCE`;
/** The library draws every mark on a 24-unit grid with 3 units of clear space: 3/24 of the edge. */
const WEB3ICONS_INSET_PERMILLE = 125;
const SIMPLE_ICONS_VERSION = "16.33.0";
const SIMPLE_ICONS_CDN = `https://cdn.jsdelivr.net/npm/simple-icons@${SIMPLE_ICONS_VERSION}`;
const SIMPLE_ICONS_LICENCE_URL = `https://github.com/simple-icons/simple-icons/blob/${SIMPLE_ICONS_VERSION}/LICENSE.md`;
const HYPERLIQUID_APP = "https://app.hyperliquid.xyz";

const DARK_INK = "#000000";
const LIGHT_INK = "#FFFFFF";
const FETCH_TIMEOUT_MS = 30_000;
const ISO_DATE_CHARS = 10;
const HEX_RADIX = 16;
const HEX_CHANNEL_CHARS = 2;
const CHANNEL_MAX = 255;
/** Rec. 601 luma weights; a brand colour darker / lighter than these bounds needs the opposite ground. */
const LUMA_RED = 0.299;
const LUMA_GREEN = 0.587;
const LUMA_BLUE = 0.114;
const LUMA_NEEDS_LIGHT_GROUND = 0.2;
const LUMA_NEEDS_DARK_GROUND = 0.85;

type Presentation = Pick<ArtFile, "insetPermille" | "surface" | "shape" | "crop">;

interface Piece {
  variant: MarkVariant;
  /** File name inside sources/<key>/. */
  name: string;
  url: string;
  svg: string;
  present: Presentation;
  derived?: Derivation;
}

interface Fetched {
  provenance: Provenance;
  pageUrl: string;
  licence: string;
  usage: string;
  pieces: Piece[];
}

const sha256 = (text: string): string => createHash("sha256").update(text).digest("hex");
const pathOf = (key: string, name: string): string => `${SOURCES}/${key}/${name}`;

async function get(url: string): Promise<string> {
  const res = await fetch(url, { redirect: "follow", signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) });
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return res.text();
}

/** A delivered file must be a self-contained vector: no raster, no live text, nothing foreign. */
async function getSvg(url: string): Promise<string> {
  const svg = await get(url);
  if (!/<svg\b/.test(svg)) throw new Error(`${url}: not an SVG`);
  const bad = /<(image|text|foreignObject)\b/.exec(svg);
  if (bad) throw new Error(`${url}: contains <${bad[1]}> — pick another source for this mark`);
  return svg;
}

function viewBoxOf(svg: string, label: string): string {
  const declared = /<svg[^>]*\sviewBox="([^"]+)"/.exec(svg)?.[1];
  if (!declared) throw new Error(`${label}: no viewBox`);
  return declared
    .trim()
    .split(/[\s,]+/)
    .join(" ");
}

/** The one paint a mono silhouette uses (so recolouring it is a single literal substitution). */
function soleInk(svg: string, label: string): string {
  const paints = [...svg.matchAll(/(?:fill|stroke|stop-color)="([^"]+)"/g)].map((m) => m[1] ?? "");
  const inks = [...new Set(paints.filter((p) => p !== "none"))];
  if (inks.length !== 1 || inks[0] === undefined)
    throw new Error(`${label}: expected one ink, found ${inks.join(", ")}`);
  return inks[0];
}

async function fromWeb3Icons(key: string, spec: Extract<FetchSpec, { from: "web3icons" }>): Promise<Fetched> {
  const url = (variant: string) => `${WEB3ICONS_RAW}/${spec.group}/${variant}/${spec.name}.svg`;
  const name = (variant: string, suffix = "") => `web3icons-${spec.group}-${variant}-${spec.name}${suffix}.svg`;
  const pieces: Piece[] = [];
  for (const take of spec.take) {
    if (take === "disc") {
      const present: Presentation = { insetPermille: 0, surface: "any", shape: "disc", crop: "disc" };
      pieces.push({
        variant: "disc",
        name: name("background"),
        url: url("background"),
        svg: await getSvg(url("background")),
        present,
      });
    } else if (take === "symbol") {
      const present: Presentation = { insetPermille: WEB3ICONS_INSET_PERMILLE, surface: "any", shape: "free" };
      pieces.push({
        variant: "symbol",
        name: name("branded"),
        url: url("branded"),
        svg: await getSvg(url("branded")),
        present,
      });
    } else {
      const light = await getSvg(url("mono"));
      const derived: Derivation = {
        from: pathOf(key, name("mono")),
        recolour: { [soleInk(light, url("mono"))]: DARK_INK },
        basis: `MIT License (${WEB3ICONS_LICENCE_URL}): "the rights to use, copy, modify, merge, publish, distribute" — the library's one-ink silhouette, recoloured to dark ink for light grounds.`,
      };
      const base = { insetPermille: WEB3ICONS_INSET_PERMILLE, shape: "free" } as const;
      pieces.push({
        variant: "monoLight",
        name: name("mono"),
        url: url("mono"),
        svg: light,
        present: { ...base, surface: "dark" },
      });
      pieces.push({
        variant: "monoDark",
        name: name("mono", "-dark"),
        url: url("mono"),
        svg: deriveSvg(light, derived),
        present: { ...base, surface: "light" },
        derived,
      });
    }
  }
  return {
    provenance: "open-library",
    pageUrl: `${WEB3ICONS_REPO}/tree/${WEB3ICONS_COMMIT}/raw-svgs/${spec.group}`,
    licence: `MIT License, "Copyright (c) 2024 0xa3k5" (${WEB3ICONS_LICENCE_URL}): "Permission is hereby granted, free of charge … to use, copy, modify, merge, publish, distribute". The licence covers the icon files; the mark itself stays its owner's trademark and is used nominatively, only to identify the asset, network or venue it belongs to.`,
    usage:
      "Drawn on the library's 24-unit grid (3 units of clear space). The disc is the library's brand-colour background variant clipped to its inscribed circle by codegen; the dark-ink silhouette is the white one recoloured.",
    pieces,
  };
}

async function fromHyperliquid(spec: Extract<FetchSpec, { from: "hyperliquid" }>): Promise<Fetched> {
  const url = `${HYPERLIQUID_APP}/coins/${spec.coin}.svg`;
  const present: Presentation = { insetPermille: 0, surface: "any", shape: "disc" };
  return {
    provenance: "venue-metadata",
    pageUrl: `${HYPERLIQUID_APP}/trade/${spec.coin}`,
    licence: `No separate licence: this is the icon Hyperliquid's own app serves for the ${spec.coin} market it lists (${url}), i.e. venue-published instrument metadata. The mark belongs to its project and is used nominatively, only to identify that asset beside its ticker.`,
    usage: "A full disc as served; shown only for the asset itself, never as a venue badge.",
    pieces: [{ variant: "disc", name: `hyperliquid-coin-${spec.coin}.svg`, url, svg: await getSvg(url), present }],
  };
}

interface SimpleIcon {
  title: string;
  slug?: string;
  hex: string;
}

let simpleIconsData: Promise<SimpleIcon[]> | undefined;
function simpleIcon(slug: string): Promise<SimpleIcon> {
  simpleIconsData ??= get(`${SIMPLE_ICONS_CDN}/data/simple-icons.json`).then(
    (text) => JSON.parse(text) as SimpleIcon[],
  );
  return simpleIconsData.then((icons) => {
    const found = icons.find((i) => (i.slug ?? i.title.toLowerCase().replace(/[^a-z0-9]/g, "")) === slug);
    if (!found) throw new Error(`simple-icons: no data entry for "${slug}"`);
    return found;
  });
}

/** Which ground a flat brand colour reads on. */
function surfaceFor(hex: string): ArtFile["surface"] {
  const channel = (index: number) =>
    Number.parseInt(hex.slice(index * HEX_CHANNEL_CHARS, (index + 1) * HEX_CHANNEL_CHARS), HEX_RADIX) / CHANNEL_MAX;
  const luma = LUMA_RED * channel(0) + LUMA_GREEN * channel(1) + LUMA_BLUE * channel(2);
  if (luma < LUMA_NEEDS_LIGHT_GROUND) return "light";
  return luma > LUMA_NEEDS_DARK_GROUND ? "dark" : "any";
}

async function fromSimpleIcons(key: string, spec: Extract<FetchSpec, { from: "simple-icons" }>): Promise<Fetched> {
  const url = `${SIMPLE_ICONS_CDN}/icons/${spec.slug}.svg`;
  const [delivered, icon] = await Promise.all([getSvg(url), simpleIcon(spec.slug)]);
  const name = (suffix = "") => `simple-icons-${spec.slug}${suffix}.svg`;
  const base = { insetPermille: 0, shape: "free" } as const;
  const fill = (rootFill: string): Derivation => ({
    from: pathOf(key, name()),
    recolour: {},
    rootFill,
    basis: `CC0 1.0 Universal (${SIMPLE_ICONS_LICENCE_URL}) dedicates the icon file to the public domain; the library itself serves each icon in a chosen colour (https://cdn.simpleicons.org/[SLUG]/[COLOR]).`,
  });
  const brand = fill(`#${icon.hex}`);
  const light = fill(LIGHT_INK);
  return {
    provenance: "open-library",
    pageUrl: `https://simpleicons.org/?q=${spec.slug}`,
    licence: `CC0 1.0 Universal (${SIMPLE_ICONS_LICENCE_URL}) for the icon file. The library's DISCLAIMER.md: the brand stays its owner's trademark; used nominatively, to identify the underlying company of an instrument, never as an endorsement. Brand colour #${icon.hex} is the value in the library's data file.`,
    usage: `Always beside the instrument's ticker and type (study 08: company artwork never drops the perp / tokenized distinction). The colour mark is the one-path icon filled with #${icon.hex}.`,
    pieces: [
      { variant: "monoDark", name: name(), url, svg: delivered, present: { ...base, surface: "light" } },
      {
        variant: "symbol",
        name: name("-brand"),
        url,
        svg: deriveSvg(delivered, brand),
        present: { ...base, surface: surfaceFor(icon.hex) },
        derived: brand,
      },
      {
        variant: "monoLight",
        name: name("-light"),
        url,
        svg: deriveSvg(delivered, light),
        present: { ...base, surface: "dark" },
        derived: light,
      },
    ],
  };
}

function fetchEntry(entry: CatalogEntry): Promise<Fetched> {
  const { spec } = entry;
  if (spec.from === "web3icons") return fromWeb3Icons(entry.key, spec);
  if (spec.from === "hyperliquid") return fromHyperliquid(spec);
  return fromSimpleIcons(entry.key, spec);
}

function toRecord(entry: CatalogEntry, fetched: Fetched, previous: ArtSource | undefined, today: string): ArtSource {
  const variants: Partial<Record<MarkVariant, ArtFile>> = {};
  for (const piece of fetched.pieces) {
    const path = pathOf(entry.key, piece.name);
    mkdirSync(dirname(join(ROOT, path)), { recursive: true });
    writeFileSync(join(ROOT, path), piece.svg);
    variants[piece.variant] = {
      path,
      url: piece.url,
      sha256: sha256(piece.svg),
      viewBox: viewBoxOf(piece.svg, piece.url),
      ...piece.present,
      ...(piece.derived ? { derived: piece.derived } : {}),
    };
  }
  const unchanged =
    previous !== undefined &&
    JSON.stringify(Object.values(previous.variants).map((f) => f.sha256)) ===
      JSON.stringify(Object.values(variants).map((f) => f.sha256));
  return {
    key: entry.key,
    owner: entry.owner,
    provenance: fetched.provenance,
    pageUrl: fetched.pageUrl,
    licence: fetched.licence,
    retrieved: unchanged ? previous.retrieved : today,
    usage: fetched.usage,
    variants,
  };
}

async function main(): Promise<void> {
  const previous: readonly ArtSource[] = existsSync(OUT) ? (await import(pathToFileURL(OUT).href)).FETCHED_ART : [];
  const today = new Date().toISOString().slice(0, ISO_DATE_CHARS);
  const records: ArtSource[] = [];
  for (const entry of CATALOG) {
    const fetched = await fetchEntry(entry);
    const record = toRecord(
      entry,
      fetched,
      previous.find((p) => p.key === entry.key),
      today,
    );
    records.push(record);
    console.log(`${entry.key} ← ${entry.spec.from}: ${Object.keys(record.variants).join(", ")}`);
  }
  mkdirSync(dirname(OUT), { recursive: true });
  const body = `export const FETCHED_ART: readonly ArtSource[] = ${JSON.stringify(records, null, 2)};\n`;
  writeFileSync(OUT, `${HEADER}\nimport type { ArtSource } from "../../types.ts";\n\n${body}`);
  console.log(`fetched ${records.length} marks → ${OUT.slice(ROOT.length + 1)} — now run codegen`);
}

await main();
