"""Local evidence extraction; never uploads or changes the source recordings."""
import argparse
import hashlib
import json
import math
import subprocess
import os
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
CACHE = Path(os.environ.get("REFERENCE_CACHE", "/tmp/metropolis-reference-inspection/cache"))
SOURCES = {
    "R1": Path("/Users/abu/Downloads/ScreenRecording_09-30-2026 20-02-13_1.MP4"),
    "R2": Path("/Users/abu/Downloads/ScreenRecording_09-30-2026 20-04-41_1.MP4"),
    "R3": Path("/Users/abu/Downloads/ScreenRecording_09-30-2026 20-10-56_1.MP4"),
}

def run(args):
    return subprocess.check_output(args, text=True)

def stamp(t):
    return f"{int(t)//60:02d}:{t%60:05.2f}"

def sheet(paths, times, output, title, width=300, cols=4):
    h = round(width * 2622 / 1206)
    header, label, gap = 42, 30, 12
    rows = math.ceil(len(paths)/cols)
    canvas = Image.new("RGB", (cols*(width+gap)+gap, header+rows*(h+label+gap)+gap), "#17191e")
    draw = ImageDraw.Draw(canvas)
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Menlo.ttc", 18)
    except OSError:
        font = ImageFont.load_default()
    draw.text((gap, 10), title, fill="white", font=font)
    for i, (path,t) in enumerate(zip(paths,times)):
        x, y = gap+(i%cols)*(width+gap), header+(i//cols)*(h+label+gap)
        draw.text((x,y), stamp(t), fill="white", font=font)
        canvas.paste(Image.open(path).convert("RGB").resize((width,h)), (x,y+label))
    output.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output, quality=90)

def extract(key):
    source = SOURCES[key]
    dest = CACHE / key / "samples"
    dest.mkdir(parents=True,exist_ok=True)
    meta = json.loads(run(["ffprobe","-v","quiet","-print_format","json","-show_format","-show_streams",str(source)]))
    duration = float(meta["format"]["duration"])
    run(["ffmpeg","-hide_banner","-loglevel","error","-y","-i",str(source),"-vf","fps=2,scale=402:-1","-q:v","3",str(dest/"%05d.jpg")])
    allpaths = sorted(dest.glob("*.jpg"))
    # Retained overview sheets are generated by curate.py, which redacts accounts.
    digest=hashlib.sha256(source.read_bytes()).hexdigest()
    video=next(s for s in meta["streams"] if s["codec_type"]=="video")
    (ROOT/"evidence"/key/"metadata.json").write_text(json.dumps({"id":key,"source":str(source),"sha256":digest,"duration_seconds":duration,"width":video["width"],"height":video["height"],"average_frame_rate":video["avg_frame_rate"],"variable_frame_rate":True,"sample_interval_seconds":0.5,"sample_time_caveat":"fps filter rounds to a uniform output grid; sample timestamps are approximate. Motion measurements use separately decoded source timestamps.","samples":len(allpaths),"ffprobe":meta},indent=2))
    print(f"{key}: {duration:.3f}s, {len(allpaths)} samples, {math.ceil(len(overview)/16)} overview sheets")

if __name__ == "__main__":
    parser=argparse.ArgumentParser()
    parser.add_argument("recording",choices=SOURCES)
    args=parser.parse_args()
    extract(args.recording)
