"""Regenerate context/00-hackathon/prizes-and-bounties.md from the portal capture.

Every amount, split, eligible track and requirement is copied from _portal/api/catalog.json.
Re-run after re-capturing the portal:  python3 context/_tools/build_prizes.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
catalog = json.loads((ROOT / "_portal/api/catalog.json").read_text())
file_map = json.loads((ROOT / "_portal/api/bounty-file-map.json").read_text())
tracks = sorted(catalog["tracks"], key=lambda t: t["sortOrder"])
track_short = {t["id"]: f"{n:02d} {t['name']}" for n, t in enumerate(tracks, 1)}


def sponsor(b):
    s = b.get("sponsor") or b.get("partner")
    return s.get("name") if isinstance(s, dict) else s


def cell(text):
    return (text or "").replace("\n", " ").replace("|", "/").strip()


def extra_fields(b):
    reqs = [r for r in (b.get("requirements") or []) if r.get("prompt") != "Test test test"]
    return "; ".join(f"{r['prompt']}" + (" (required)" if r.get("required") else "") for r in reqs) or "—"


bounties = sorted(catalog["bounties"], key=lambda b: (b["trackId"] is not None, track_short.get(b["trackId"], ""), b["sortOrder"]))

lines = [
    "# Prizes, Bounties and Perks",
    "",
    "> **Source of truth:** the logged-in portal, captured 2026-09-29 (`_portal/api/catalog.json`, `_portal/pages/prizes.md`, `_portal/pages/rules.md`). "
    "Generated by `context/_tools/build_prizes.py`. Don't hand-edit the tables; re-run the script.",
    "",
    "## How it works (official)",
    "- *\"Choose one primary track, then add as many sponsor bounties as you'd like. Each bounty lists what it needs. You complete those fields when you submit.\"* (Tracks & Bounties page)",
    "- *\"Each one names its track, and the ones marked All tracks pair with any.\"* A bounty tied to a track is only open to projects in **that** track.",
    "- *\"Main-track prizes are separate and stack with sponsor bounties.\"* (Prizes page)",
    "- Rules §5.2: sponsor bounties are judged on *Adherence to the published bounty requirements (40%), Technical Implementation (30%), Monad Integration (20%), Innovation (10%)*.",
    "- Rules §6.1: prizes are paid in **USDC or equivalent stablecoin** to the team contact's wallet; **KYC may be required**.",
    "",
    "## Main prizes: $145,000 (rules §3.2)",
    "| Prize | Amount |",
    "|---|---|",
    "| Grand Champion (Overall Winner) | $25,000, *\"awarded at the judges' discretion\"* |",
]
for t in tracks:
    lines.append(f"| {track_short[t['id']]} | {t['prize']}: {t['prizeBreakdown']} |")

lines += [
    "",
    f"## All {len(bounties)} sponsor bounties (official)",
    "Sorted: **All-tracks** first, then bounties tied to a specific track.",
    "",
    "| Eligible track | Sponsor | Bounty | Prize | Split | What it asks for (verbatim) | Extra submission fields | Full text |",
    "|---|---|---|---|---|---|---|---|",
]
for b in bounties:
    track = "**All tracks**" if not b["trackId"] else track_short[b["trackId"]]
    lines.append(
        f"| {track} | {sponsor(b)} | {b['name']} | {cell(b['prize'])} | {cell(b.get('prizeBreakdown'))} | {cell(b['summary'])} | "
        f"{cell(extra_fields(b))} | [open](../_portal/bounties/{file_map[b['slug']]}) |"
    )

lines += [
    "",
    "Notes:",
    "- The *Best Community Team Project* bounty has one required submission field whose captured label is literally \"Test test test\" (probably a placeholder). Check it when the submission form opens.",
    "- Bounty criteria are in each full-text file. Several bounties **disqualify** shallow use: e.g. Privy says *\"login-only integrations will not qualify\"*; Kimi says *\"not bolted on as a chatbot widget\"*.",
    "",
    "## Prize-pool contributions: given to winners (Prizes page, verbatim)",
    "*\"Estimated services, plans, and rebates for winning teams. Values are tracker headline estimates and sponsor terms apply.\"*",
    "",
    "| Sponsor | What winners get | Up to |",
    "|---|---|---|",
    "| ack3 | A security scan for every winning team. | $15,000 |",
    "| Chainstack | Annual Pro plans for the Track 01 winners and the Grand Champion. | $10,000 |",
    "| Crouton Digital | Three months of unlimited-usage RPC API access for winning teams. | $10,000 |",
    "| Zerion | Three months of the Zerion API Builder Plan for all winners. | $6,000 |",
    "| Envio | Two months of Cloud hosting free, then a third month at 50% off. | $5,000 |",
    "| PingBusiness | A merchant rebate based on qualifying cumulative transaction volume. | $20,000 |",
    "",
    "The public marketing page also lists **Mercuryo** ($10K credits + integration support) and **Spectrum Nodes** ($3K). They are **not** on the portal's Prizes page, so treat them as unconfirmed.",
    "",
    "## Participant perks: claim now (Resources page; *\"One voucher per team for each resource\"*)",
    "| Perk | Access | Eligibility | How to claim (from the sponsor's claim page) |",
    "|---|---|---|---|",
    "| QuickNode Build plan | 3 months | **New accounts only** | Usage & Billing → Build plan (monthly) → coupon `METROPOLISQN` at checkout (case sensitive). Help: @sensahill on Telegram. [claim page](../_portal/pages/claim-quicknode.md) |",
    "| Tenderly Pro tier | Org access until 3 Nov, 10 seats | All teams (set up *after your team is formed and submitted*) | Request via https://forms.monad.xyz/r/metropolis-tenderly-access. One email per team; no confirmation email. [claim page](../_portal/pages/claim-tenderly.md) |",
    "| Zerion API Builder | 1 month (250K req/month, 10 RPS) | All teams | dashboard.zerion.io → My plan → Builder → promo `METROPOLIS100` at Stripe checkout. [claim page](../_portal/pages/claim-zerion.md) |",
    "",
    "Dwellir and Spectrum Nodes free plans appear on the public page but **not** in the portal's Resources.",
]
out = ROOT / "00-hackathon/prizes-and-bounties.md"
out.write_text("\n".join(lines) + "\n")
print("wrote", out, "bounties:", len(bounties))
