// Generated by scripts/contracts-export.mjs — do not edit.
export type ContractEntry = {
  readonly address: `0x${string}`;
  readonly initCodeHash: `0x${string}`;
  readonly startBlock: number;
  readonly indexed: boolean;
};

export type AddressBook = {
  readonly chainId: number;
  readonly contracts: Readonly<Record<string, ContractEntry>>;
};

/** Deployed contracts per chain id (143 mainnet, 10143 testnet); empty until Deploy.s.sol has run. */
export const addressBooks: Readonly<Record<number, AddressBook>> = {};
