// Generated by scripts/contracts-export.mjs — do not edit.
import book10143 from "./10143.json";

export type ContractEntry = {
  readonly address: `0x${string}`;
  readonly initCodeHash: `0x${string}`;
  readonly startBlock: number;
  readonly indexed: boolean;
};

export type AddressBook = {
  readonly chainId: number;
  readonly contracts: Readonly<Record<string, ContractEntry>>;
};

/** Deployed contracts per chain id (143 mainnet, 10143 testnet); empty until Deploy.s.sol has run. */
export const addressBooks: Readonly<Record<number, AddressBook>> = {
  10143: book10143 as AddressBook,
};
