"use client";
import dynamic from "next/dynamic";
export const GROUPS: Record<string, { id: number; name: string; author: string; url: string; dl: number; C: React.ComponentType }[]> = {
  home: [
    { id: 5214, name: "Wallet Card 2", author: "beratberkayg", url: "https://21st.dev/@beratberkayg/components/wallet-card-2", dl: 23, C: dynamic(() => import("./demos/d5214"), { ssr: false }) },
    { id: 26545, name: "Partition Bar", author: "8starlabs", url: "https://21st.dev/@8starlabs/components/partition-bar", dl: 8, C: dynamic(() => import("./demos/d26545"), { ssr: false }) },
    { id: 30538, name: "Balance Chart", author: "ssychui", url: "https://21st.dev/@ssychui/components/balance-chart", dl: 0, C: dynamic(() => import("./demos/d30538"), { ssr: false }) },
    { id: 1444, name: "Number Flow", author: "barvian", url: "https://21st.dev/@barvian/components/number-flow", dl: 297, C: dynamic(() => import("./demos/d1444"), { ssr: false }) },
    { id: 1282, name: "Number Ticker", author: "dillionverma", url: "https://21st.dev/@dillionverma/components/number-ticker", dl: 1295, C: dynamic(() => import("./demos/d1282"), { ssr: false }) },
    { id: 1666, name: "Sliding Number", author: "ibelick", url: "https://21st.dev/@ibelick/components/sliding-number", dl: 221, C: dynamic(() => import("./demos/d1666"), { ssr: false }) },
    { id: 9658, name: "Analytics Bento", author: "jatin-yadav05", url: "https://21st.dev/@jatin-yadav05/components/analytics-bento", dl: 97, C: dynamic(() => import("./demos/d9658"), { ssr: false }) },
    { id: 8704, name: "Stock Portfolio Card", author: "kavikatiyar", url: "https://21st.dev/@kavikatiyar/components/stock-portfolio-card", dl: 27, C: dynamic(() => import("./demos/d8704"), { ssr: false }) },
    { id: 4157, name: "Stats Widget", author: "ravikatiyar162", url: "https://21st.dev/@ravikatiyar162/components/stats-widget", dl: 74, C: dynamic(() => import("./demos/d4157"), { ssr: false }) },
    { id: 9659, name: "Progress Bar", author: "jatin-yadav05", url: "https://21st.dev/@jatin-yadav05/components/progress-bar", dl: 47, C: dynamic(() => import("./demos/d9659"), { ssr: false }) },
  ],
  markets: [
    { id: 20110, name: "Market Watchlist", author: "ssychui", url: "https://21st.dev/@ssychui/components/market-watchlist", dl: 19, C: dynamic(() => import("./demos/d20110"), { ssr: false }) },
    { id: 8034, name: "Stock Card", author: "ravikatiyar162", url: "https://21st.dev/@ravikatiyar162/components/stock-card", dl: 29, C: dynamic(() => import("./demos/d8034"), { ssr: false }) },
    { id: 9045, name: "Financial Markets Table", author: "isaiahbjork", url: "https://21st.dev/@isaiahbjork/components/financial-markets-table", dl: 76, C: dynamic(() => import("./demos/d9045"), { ssr: false }) },
    { id: 22249, name: "Market Snapshot", author: "ssychui", url: "https://21st.dev/@ssychui/components/market-snapshot", dl: 8, C: dynamic(() => import("./demos/d22249"), { ssr: false }) },
    { id: 7945, name: "Asset Card", author: "ravikatiyar162", url: "https://21st.dev/@ravikatiyar162/components/asset-card", dl: 44, C: dynamic(() => import("./demos/d7945"), { ssr: false }) },
    { id: 9613, name: "Mini Chart", author: "jatin-yadav05", url: "https://21st.dev/@jatin-yadav05/components/mini-chart", dl: 132, C: dynamic(() => import("./demos/d9613"), { ssr: false }) },
    { id: 30551, name: "Market Heatmap", author: "ssychui", url: "https://21st.dev/@ssychui/components/market-heatmap", dl: 0, C: dynamic(() => import("./demos/d30551"), { ssr: false }) },
    { id: 4728, name: "Line Charts 9", author: "sean0205", url: "https://21st.dev/@sean0205/components/line-charts-9", dl: 125, C: dynamic(() => import("./demos/d4728"), { ssr: false }) },
  ],
  trade: [
    { id: 27122, name: "Swap Ticket", author: "ssychui", url: "https://21st.dev/@ssychui/components/swap-ticket", dl: 2, C: dynamic(() => import("./demos/d27122"), { ssr: false }) },
    { id: 16240, name: "BeUI Prediction Market", author: "starc007", url: "https://21st.dev/@starc007/components/be-ui-prediction-market", dl: 0, C: dynamic(() => import("./demos/d16240"), { ssr: false }) },
    { id: 2537, name: "Prediction Market Card", author: "isaiahbjork", url: "https://21st.dev/@isaiahbjork/components/prediction-market-card", dl: 32, C: dynamic(() => import("./demos/d2537"), { ssr: false }) },
    { id: 22250, name: "Candle Chart", author: "ssychui", url: "https://21st.dev/@ssychui/components/candle-chart", dl: 4, C: dynamic(() => import("./demos/d22250"), { ssr: false }) },
    { id: 29968, name: "Depth Chart", author: "arihantcodes_1f7b8c4d", url: "https://21st.dev/@arihantcodes_1f7b8c4d/components/depth-chart", dl: 0, C: dynamic(() => import("./demos/d29968"), { ssr: false }) },
    { id: 304, name: "Slider", author: "originui", url: "https://21st.dev/@originui/components/slider", dl: 805, C: dynamic(() => import("./demos/d304"), { ssr: false }) },
    { id: 1294, name: "Slider Number Flow", author: "barvian", url: "https://21st.dev/@barvian/components/slider-number-flow", dl: 125, C: dynamic(() => import("./demos/d1294"), { ssr: false }) },
    { id: 7961, name: "Segmented Button Group", author: "ruixen.ui", url: "https://21st.dev/@ruixen.ui/components/segmented-button-group", dl: 30, C: dynamic(() => import("./demos/d7961"), { ssr: false }) },
    { id: 23552, name: "Segmented Control", author: "ddoemonn", url: "https://21st.dev/@ddoemonn/components/segmented-control", dl: 69, C: dynamic(() => import("./demos/d23552"), { ssr: false }) },
    { id: 8204, name: "Currency Exchange Card", author: "ravikatiyar162", url: "https://21st.dev/@ravikatiyar162/components/currency-exchange-card", dl: 30, C: dynamic(() => import("./demos/d8204"), { ssr: false }) },
    { id: 3719, name: "Gauge", author: "designali-in", url: "https://21st.dev/@designali-in/components/gauge-1", dl: 54, C: dynamic(() => import("./demos/d3719"), { ssr: false }) },
    { id: 29280, name: "Upstash Ratelimit", author: "elements-", url: "https://21st.dev/@elements-/components/upstash-ratelimit", dl: 4, C: dynamic(() => import("./demos/d29280"), { ssr: false }) },
  ],
  confirm: [
    { id: 8, name: "Hold and Release Button", author: "kokonutd", url: "https://21st.dev/@kokonutd/components/hold-and-release-button", dl: 81, C: dynamic(() => import("./demos/d8"), { ssr: false }) },
    { id: 5107, name: "Finger Scan Button", author: "designali-in", url: "https://21st.dev/@designali-in/components/finger-scan-button", dl: 12, C: dynamic(() => import("./demos/d5107"), { ssr: false }) },
    { id: 19045, name: "Passkey Sign-In", author: "felipemenezes098", url: "https://21st.dev/@felipemenezes098/components/sign-in-4", dl: 8, C: dynamic(() => import("./demos/d19045"), { ssr: false }) },
    { id: 19036, name: "Push Approval Card", author: "felipemenezes098", url: "https://21st.dev/@felipemenezes098/components/verify-identity-3", dl: 8, C: dynamic(() => import("./demos/d19036"), { ssr: false }) },
    { id: 1245, name: "Drawer", author: "shadcn", url: "https://21st.dev/@shadcn/components/drawer", dl: 173, C: dynamic(() => import("./demos/d1245"), { ssr: false }) },
    { id: 23569, name: "Task Steps", author: "ddoemonn", url: "https://21st.dev/@ddoemonn/components/task-steps", dl: 16, C: dynamic(() => import("./demos/d23569"), { ssr: false }) },
    { id: 6492, name: "Ticket Confirmation Card", author: "ravikatiyar162", url: "https://21st.dev/@ravikatiyar162/components/ticket-confirmation-card", dl: 111, C: dynamic(() => import("./demos/d6492"), { ssr: false }) },
    { id: 9038, name: "Order Confirmation Card", author: "kavikatiyar", url: "https://21st.dev/@kavikatiyar/components/order-confirmation-card", dl: 39, C: dynamic(() => import("./demos/d9038"), { ssr: false }) },
  ],
  card: [
    { id: 1172, name: "Credit Card", author: "rynkovski", url: "https://21st.dev/@rynkovski/components/credit-card", dl: 41, C: dynamic(() => import("./demos/d1172"), { ssr: false }) },
    { id: 29187, name: "Wallet Card", author: "educalvolpz", url: "https://21st.dev/@educalvolpz/components/wallet-card", dl: 0, C: dynamic(() => import("./demos/d29187"), { ssr: false }) },
    { id: 5276, name: "Credit  or Debit Card", author: "ravikatiyar162", url: "https://21st.dev/@ravikatiyar162/components/credit-debit-card", dl: 34, C: dynamic(() => import("./demos/d5276"), { ssr: false }) },
    { id: 9217, name: "HolographicCard", author: "dhileepkumargm", url: "https://21st.dev/@dhileepkumargm/components/holographic-card", dl: 125, C: dynamic(() => import("./demos/d9217"), { ssr: false }) },
    { id: 3206, name: "Liquid Glass Card", author: "designali-in", url: "https://21st.dev/@designali-in/components/liquid-glass-card", dl: 98, C: dynamic(() => import("./demos/d3206"), { ssr: false }) },
    { id: 2696, name: "Glass Card ", author: "Smit-Prajapati", url: "https://21st.dev/@Smit-Prajapati/components/glass-card", dl: 181, C: dynamic(() => import("./demos/d2696"), { ssr: false }) },
    { id: 1436, name: "3D Flip Card", author: "ayushmxxn", url: "https://21st.dev/@ayushmxxn/components/3d-flip-card", dl: 89, C: dynamic(() => import("./demos/d1436"), { ssr: false }) },
    { id: 25102, name: "Express Wallets", author: "felipemenezes098", url: "https://21st.dev/@felipemenezes098/components/payment-3", dl: 2, C: dynamic(() => import("./demos/d25102"), { ssr: false }) },
    { id: 7633, name: "Card", author: "kavikatiyar", url: "https://21st.dev/@kavikatiyar/components/card-5", dl: 12, C: dynamic(() => import("./demos/d7633"), { ssr: false }) },
  ],
  fund: [
    { id: 6838, name: "QR Code Generator", author: "user_xn1cklas", url: "https://21st.dev/@user_xn1cklas/components/qr-code-generator", dl: 25, C: dynamic(() => import("./demos/d6838"), { ssr: false }) },
    { id: 6170, name: "QR Code", author: "anubra266", url: "https://21st.dev/@anubra266/components/qr-code", dl: 28, C: dynamic(() => import("./demos/d6170"), { ssr: false }) },
    { id: 16251, name: "BeUI Multi-chain Swap ", author: "starc007", url: "https://21st.dev/@starc007/components/be-ui-multi-chain-swap", dl: 6, C: dynamic(() => import("./demos/d16251"), { ssr: false }) },
    { id: 9552, name: "Copy Code Button", author: "minhxthanh", url: "https://21st.dev/@minhxthanh/components/copy-code-button", dl: 37, C: dynamic(() => import("./demos/d9552"), { ssr: false }) },
  ],
  nav: [
    { id: 10458, name: "Bottom Menu", author: "0xUrvish", url: "https://21st.dev/@0xUrvish/components/bottom-menu", dl: 34, C: dynamic(() => import("./demos/d10458"), { ssr: false }) },
    { id: 574, name: "Bottom menu", author: "yadwinder", url: "https://21st.dev/@yadwinder/components/bottom-menu", dl: 286, C: dynamic(() => import("./demos/d574"), { ssr: false }) },
    { id: 7878, name: "Pill Morph Tabs", author: "ruixen.ui", url: "https://21st.dev/@ruixen.ui/components/pill-morph-tabs", dl: 63, C: dynamic(() => import("./demos/d7878"), { ssr: false }) },
    { id: 1597, name: "Vercel Tabs", author: "yadwinder", url: "https://21st.dev/@yadwinder/components/vercel-tabs", dl: 556, C: dynamic(() => import("./demos/d1597"), { ssr: false }) },
    { id: 4086, name: "Tabs", author: "sean0205", url: "https://21st.dev/@sean0205/components/tabs", dl: 318, C: dynamic(() => import("./demos/d4086"), { ssr: false }) },
    { id: 3058, name: "Dynamic Island", author: "cult-ui", url: "https://21st.dev/@cult-ui/components/dynamic-island", dl: 27, C: dynamic(() => import("./demos/d3058"), { ssr: false }) },
  ],
  states: [
    { id: 1435, name: "Empty State", author: "serafimcloud", url: "https://21st.dev/@serafimcloud/components/empty-state", dl: 793, C: dynamic(() => import("./demos/d1435"), { ssr: false }) },
    { id: 22302, name: "Interactive Empty State", author: "remcostoeten", url: "https://21st.dev/@remcostoeten/components/interactive-empty-state", dl: 215, C: dynamic(() => import("./demos/d22302"), { ssr: false }) },
    { id: 21518, name: "Offline Empty State", author: "bundui", url: "https://21st.dev/@bundui/components/empty8", dl: 6, C: dynamic(() => import("./demos/d21518"), { ssr: false }) },
    { id: 29348, name: "500 Server Error Page", author: "olewandowski1", url: "https://21st.dev/@olewandowski1/components/error-3", dl: 4, C: dynamic(() => import("./demos/d29348"), { ssr: false }) },
    { id: 886, name: "Sonner", author: "shadcn", url: "https://21st.dev/@shadcn/components/sonner", dl: 374, C: dynamic(() => import("./demos/d886"), { ssr: false }) },
    { id: 8863, name: "Alert Toast", author: "lavikatiyar", url: "https://21st.dev/@lavikatiyar/components/alert-toast", dl: 83, C: dynamic(() => import("./demos/d8863"), { ssr: false }) },
    { id: 1588, name: "Skeleton", author: "shadcn", url: "https://21st.dev/@shadcn/components/skeleton", dl: 1097, C: dynamic(() => import("./demos/d1588"), { ssr: false }) },
    { id: 23557, name: "Skeleton Swap", author: "ddoemonn", url: "https://21st.dev/@ddoemonn/components/skeleton-swap", dl: 12, C: dynamic(() => import("./demos/d23557"), { ssr: false }) },
    { id: 1641, name: "Text Shimmer", author: "ibelick", url: "https://21st.dev/@ibelick/components/text-shimmer", dl: 2807, C: dynamic(() => import("./demos/d1641"), { ssr: false }) },
    { id: 23591, name: "Loading State", author: "theshanelevine", url: "https://21st.dev/@theshanelevine/components/loading-state", dl: 10, C: dynamic(() => import("./demos/d23591"), { ssr: false }) },
    { id: 843, name: "Confetti", author: "dillionverma", url: "https://21st.dev/@dillionverma/components/confetti", dl: 663, C: dynamic(() => import("./demos/d843"), { ssr: false }) },
    { id: 3166, name: "Liquid Glass Button", author: "designali-in", url: "https://21st.dev/@designali-in/components/liquid-glass-button", dl: 2911, C: dynamic(() => import("./demos/d3166"), { ssr: false }) },
    { id: 845, name: "Retro Button", author: "serafimcloud", url: "https://21st.dev/@serafimcloud/components/retro-button", dl: 62, C: dynamic(() => import("./demos/d845"), { ssr: false }) },
    { id: 3223, name: "Apple Activity Ring", author: "kokonutd", url: "https://21st.dev/@kokonutd/components/apple-activity-ring", dl: 51, C: dynamic(() => import("./demos/d3223"), { ssr: false }) },
    { id: 22228, name: "Notification List", author: "skyleen77", url: "https://21st.dev/@skyleen77/components/components-community-notification-list", dl: 5, C: dynamic(() => import("./demos/d22228"), { ssr: false }) },
  ],
};
