/**
 * Emits `src/tokens.css` from the TypeScript palette so web never hand-writes a colour.
 * Shape follows shadcn/Tailwind 4 conventions (`--background`, `--chart-1`…) so 21st components drop in re-tokenized.
 * Run: pnpm --filter @senryo/tokens emit
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ASSET_HUE, CHAIN_HUE, KINPAKU, QR } from "../src/marks.ts";
import { DARK, LIGHT, type Palette } from "../src/palette.ts";
import { FONT, HAIRLINE_PX, MOTION, RADIUS, SPACE, TYPE } from "../src/scale.ts";

const toKebab = (role: string) => role.replace(/([a-z])([A-Z0-9])/g, "$1-$2").toLowerCase();

function block(selector: string, palette: Palette): string {
  const lines = Object.entries(palette).map(([role, value]) => `  --${toKebab(role)}: ${value};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
}

const ROOT_PX = 16;
const rem = (px: number) => `${px / ROOT_PX}rem`;

/** Type roles → `--type-<role>-size|leading|tracking|weight` (web maps them onto Tailwind `--text-*` in @theme). */
function typeLines(): string[] {
  return Object.entries(TYPE).flatMap(([role, t]) => {
    const name = toKebab(role);
    return [
      `  --type-${name}-size: ${rem(t.size)};`,
      `  --type-${name}-leading: ${rem(t.lineHeight)};`,
      `  --type-${name}-tracking: ${t.tracking}em;`,
      `  --type-${name}-weight: ${t.weight};`,
    ];
  });
}

const [e1, e2, e3, e4] = MOTION.easing;
const header = "/* Generated by packages/tokens/scripts/emit-css.ts — do not edit by hand. */";
const shared = [
  ":root {",
  `  --radius: ${rem(RADIUS.sm)};`,
  `  --hairline: ${HAIRLINE_PX}px;`,
  `  --font-sans-family: "${FONT.sans}", ui-sans-serif, system-ui;`,
  `  --font-display-family: "${FONT.display}", "${FONT.sans}", ui-sans-serif, system-ui;`,
  `  --font-mono-family: "${FONT.mono}", ui-sans-serif, system-ui;`,
  `  --motion-fast: ${MOTION.fastMs}ms;`,
  `  --motion-base: ${MOTION.baseMs}ms;`,
  `  --motion-slow: ${MOTION.slowMs}ms;`,
  `  --motion-ease: cubic-bezier(${e1}, ${e2}, ${e3}, ${e4});`,
  ...Object.entries(SPACE).map(([k, v]) => `  --space-${k}: ${rem(v)};`),
  ...typeLines(),
  ...Object.entries(KINPAKU).map(([k, v]) => `  --kinpaku-${toKebab(k)}: ${v};`),
  `  --qr-ink: ${QR.ink};`,
  `  --qr-paper: ${QR.paper};`,
  ...Object.entries(CHAIN_HUE).map(([k, v]) => `  --chain-${k}: ${v};`),
  ...Object.entries(ASSET_HUE).map(([k, v]) => `  --asset-${k.replace("/", "").toLowerCase()}: ${v};`),
  "}",
].join("\n");
const css = [header, shared, block(":root, .dark", DARK), block(".light", LIGHT), ""].join("\n\n");

const target = fileURLToPath(new URL("../src/tokens.css", import.meta.url));
writeFileSync(target, css);
console.log(`wrote ${target}`);
