/**
 * Emits `src/tokens.css` from the TypeScript tokens so web never hand-writes a colour, size or duration.
 * Shape follows shadcn/Tailwind 4 conventions (`--background`, `--chart-1`…) so 21st components drop in re-tokenized;
 * the Living Lacquer roles follow as `--text-2`, `--glass-tint`, `--fan-circle`… (D-168/D-191).
 * Run: pnpm --filter @senryo/tokens emit
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { KINPAKU, MATERIAL, QR, SCENE_FIELD } from "../src/marks.ts";
import { DARK, LIGHT, type Palette } from "../src/palette.ts";
import { ELEVATION, FONT, HAIRLINE_PX, MOTION, RADIUS, SPACE, TYPE } from "../src/scale.ts";

const toKebab = (role: string) => role.replace(/([a-z])([A-Z0-9])/g, "$1-$2").toLowerCase();

function block(selector: string, palette: Palette): string {
  const lines = Object.entries(palette).map(([role, value]) => `  --${toKebab(role)}: ${value};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
}

const ROOT_PX = 16;
const rem = (px: number) => `${px / ROOT_PX}rem`;

/** Type roles → `--type-<role>-size|leading|tracking|weight` (web maps them onto Tailwind `--text-*` in @theme). */
function typeLines(): string[] {
  return Object.entries(TYPE).flatMap(([role, t]) => {
    const name = toKebab(role);
    return [
      `  --type-${name}-size: ${rem(t.size)};`,
      `  --type-${name}-leading: ${rem(t.lineHeight)};`,
      `  --type-${name}-tracking: ${t.tracking}em;`,
      `  --type-${name}-weight: ${t.weight};`,
    ];
  });
}

/** Durations only: `*Ms` keys become `--motion-<name>` in ms (springs stay on mobile; CSS has no physics spring). */
function motionLines(): string[] {
  return Object.entries(MOTION)
    .filter(([key, value]) => key.endsWith("Ms") && typeof value === "number")
    .map(([key, value]) => `  --motion-${toKebab(key.slice(0, -2))}: ${value}ms;`);
}

const radiusLines = Object.entries(RADIUS).map(([k, v]) => `  --radius-step-${k}: ${rem(v)};`);
const elevationLines = Object.entries(ELEVATION).map(
  ([k, e]) => `  --elevation-${k}: ${e.x}px ${e.y}px ${e.blur}px ${e.spread}px ${e.color};`,
);
const materialLines = Object.entries(MATERIAL).flatMap(([material, ramp]) =>
  Object.entries(ramp).map(([stop, v]) => `  --${toKebab(material)}-${stop}: ${v};`),
);

const [e1, e2, e3, e4] = MOTION.easing;
const header = "/* Generated by packages/tokens/scripts/emit-css.ts — do not edit by hand. */";
const shared = [
  ":root {",
  `  --radius: ${rem(RADIUS.sm)};`,
  ...radiusLines,
  `  --hairline: ${HAIRLINE_PX}px;`,
  `  --font-sans-family: "${FONT.sans}", "${FONT.jp}", ui-sans-serif, system-ui;`,
  `  --font-display-family: "${FONT.display}", "${FONT.sans}", "${FONT.jp}", ui-sans-serif, system-ui;`,
  `  --font-mono-family: "${FONT.mono}", "${FONT.jp}", ui-sans-serif, system-ui;`,
  ...motionLines(),
  `  --motion-ease: cubic-bezier(${e1}, ${e2}, ${e3}, ${e4});`,
  `  --header-collapse-distance: ${MOTION.headerCollapseDistance}px;`,
  ...Object.entries(SPACE).map(([k, v]) => `  --space-${toKebab(k)}: ${rem(v)};`),
  ...typeLines(),
  ...elevationLines,
  ...materialLines,
  ...Object.entries(KINPAKU).map(([k, v]) => `  --kinpaku-${toKebab(k)}: ${v};`),
  ...Object.entries(SCENE_FIELD).map(([k, v]) => `  --scene-${k}: ${v};`),
  `  --qr-ink: ${QR.ink};`,
  `  --qr-paper: ${QR.paper};`,
  "}",
].join("\n");
const css = [header, shared, block(":root, .dark", DARK), block(".light", LIGHT), ""].join("\n\n");

const target = fileURLToPath(new URL("../src/tokens.css", import.meta.url));
writeFileSync(target, css);
console.log(`wrote ${target}`);
