/**
 * J11 spot-token list generator (S1b.16) → packages/config/src/generated/spot-tokens.ts (+ spot-tokens.dropped.json).
 *
 *   pnpm --filter @senryo/drive spot-tokens          # then: pnpm --filter @senryo/identity run fetch && … codegen
 *
 * 1. Candidates: every 143 token in `monad-crypto/token-list` at the pinned commit (`MONAD_TOKEN_LIST`), minus USDC and
 *    AUSD (the quote side; swapped as collateral by F26) and WMON (native MON is listed as itself).
 * 2. Discovery (keyless): GeckoTerminal indexes Uniswap v4 on Monad with the PoolId as the pool address. Tokens with
 *    at least `MIN_TOKEN_RESERVE_USD` across Monad DEXs get their pool list; v4 pools against USDC, AUSD or native MON
 *    are kept. (HyperSync `Initialize` logs were the first choice; the project's Envio token is saturated by the
 *    production indexer, and a generator must not starve it.)
 * 3. Keys onchain: PositionManager `poolKeys(bytes25)` → PoolKey, re-hashed to the PoolId (a mismatch is dropped);
 *    hooked pools are dropped (a hook can reprice or charge any swap). StateView slot0 + liquidity must be live.
 * 4. Depth: each token's routes from USDC (direct, via the AUSD/USDC stable pool, or via MON's own route) are quoted
 *    on the v4 Quoter for `SPOT_REFERENCE_USD` of USDC; the best output wins. A token is listed only when that buy's
 *    price impact beyond the LP fees is ≤ `MAX_LISTING_IMPACT_BPS`, and its onchain `decimals()` matches the list.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type Address,
  createReadClient,
  erc20Abi,
  findStablePool,
  getAddress,
  type Hex,
  isLive,
  type PoolKey,
  poolIdOf,
  quoteSpot,
  readPoolStates,
  zeroAddress,
} from "@senryo/chain";
import {
  GECKOTERMINAL_API,
  GECKOTERMINAL_NETWORK,
  GECKOTERMINAL_UNISWAP_V4,
  MAINNET_CHAIN_ID,
  MAINNET_EXTERNAL,
  MONAD_TOKEN_LIST,
  SPOT_NATIVE,
  SPOT_REFERENCE_USD,
  type SpotPool,
  type SpotQuote,
  type SpotToken,
} from "@senryo/config";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const OUT = join(ROOT, "packages/config/src/generated/spot-tokens.ts");
const DROPPED = join(ROOT, "packages/config/src/generated/spot-tokens.dropped.json");
const HEADER =
  "// GENERATED by scripts/drive/src/spot-tokens.ts — do not edit; re-run `pnpm --filter @senryo/drive spot-tokens`.";

/** A token whose Monad DEX reserves (all venues, GeckoTerminal) are below this can't hold a listable v4 pool. */
const MIN_TOKEN_RESERVE_USD = 10_000;
/** A $1,000 buy may move the route's price at most 2 % beyond its LP fees (real liquidity, not a dust pool). */
const MAX_LISTING_IMPACT_BPS = 200n;
/** GeckoTerminal's free tier allows 10 calls/min per IP: one call every 6.5 s keeps under it. */
const GT_MIN_INTERVAL_MS = 6_500;
const GT_RETRY_AFTER_MS = 61_000;
const GT_MULTI_MAX = 30;
const HTTP_TOO_MANY = 429;
/** `bytes25(poolId)`: "0x" + 25 bytes of hex. */
const POOL_ID_PREFIX_CHARS = 52;
const SHORT_SHA_CHARS = 8;
const ISO_DATE_CHARS = 10;
/** "0x" + 8 hex digits: enough of a PoolId to name it in a log line. */
const POOL_TAG_CHARS = 10;
const USDC_DECIMALS = 6;
const TEN = 10n;
const JSON_INDENT = 2;

interface ListToken {
  chainId: number;
  address: string;
  name: string;
  symbol: string;
  decimals: number;
  logoURI?: string;
  extensions?: { coinGeckoId?: string };
}

interface GtPool {
  attributes: { address: string; name: string; reserve_in_usd: string };
  relationships: {
    base_token: { data: { id: string } };
    quote_token: { data: { id: string } };
    dex: { data: { id: string } };
  };
}

const read = createReadClient(MAINNET_CHAIN_ID);
const { usdc, ausd, uniswapV4 } = MAINNET_EXTERNAL;
const QUOTES: Readonly<Record<string, SpotQuote>> = {
  [usdc.toLowerCase()]: "USDC",
  [ausd.toLowerCase()]: "AUSD",
  [SPOT_NATIVE]: "MON",
};
const WMON = "0x3bd359c1119da7da1d913d1c4d2b7c461115433a";
const dropped: Array<{ symbol: string; address: string; reason: string }> = [];
const drop = (t: ListToken, reason: string) => {
  dropped.push({ symbol: t.symbol, address: t.address, reason });
  console.log(`  ✗ ${t.symbol}: ${reason}`);
};

let lastGt = 0;
async function gt<T>(path: string): Promise<T> {
  const wait = lastGt + GT_MIN_INTERVAL_MS - Date.now();
  if (wait > 0) await new Promise((r) => setTimeout(r, wait));
  lastGt = Date.now();
  const res = await fetch(`${GECKOTERMINAL_API}/networks/${GECKOTERMINAL_NETWORK}${path}`, {
    headers: { accept: "application/json" },
  });
  if (res.status === HTTP_TOO_MANY) {
    await new Promise((r) => setTimeout(r, GT_RETRY_AFTER_MS));
    return gt(path);
  }
  if (!res.ok) throw new Error(`GeckoTerminal ${path}: HTTP ${res.status}`);
  return (await res.json()) as T;
}

const positionManagerAbi = [
  {
    type: "function",
    name: "poolKeys",
    stateMutability: "view",
    inputs: [{ name: "poolId", type: "bytes25" }],
    outputs: [
      { name: "currency0", type: "address" },
      { name: "currency1", type: "address" },
      { name: "fee", type: "uint24" },
      { name: "tickSpacing", type: "int24" },
      { name: "hooks", type: "address" },
    ],
  },
] as const;

/** PoolId → PoolKey via the PositionManager (only pools it has minted into are known; others come back empty). */
async function keysOf(ids: readonly Hex[]): Promise<Map<string, PoolKey>> {
  const rows = await read.multicall({
    contracts: ids.map(
      (id) =>
        ({
          address: uniswapV4.positionManager,
          abi: positionManagerAbi,
          functionName: "poolKeys",
          args: [id.slice(0, POOL_ID_PREFIX_CHARS) as Hex],
        }) as const,
    ),
    allowFailure: false,
  });
  const out = new Map<string, PoolKey>();
  ids.forEach((id, i) => {
    const [currency0, currency1, fee, tickSpacing, hooks] = rows[i] as readonly [
      Address,
      Address,
      number,
      number,
      Address,
    ];
    const key = { currency0: getAddress(currency0), currency1: getAddress(currency1), fee, tickSpacing, hooks };
    if (poolIdOf(key).toLowerCase() === id.toLowerCase()) out.set(id.toLowerCase(), key);
  });
  return out;
}

const pool = (key: PoolKey): SpotPool => ({ key, poolId: poolIdOf(key) });
const refUsdc = BigInt(SPOT_REFERENCE_USD) * TEN ** BigInt(USDC_DECIMALS);

function provisional(t: ListToken, quote: SpotQuote, own: SpotPool, route: SpotPool[]): SpotToken {
  const native = t.address.toLowerCase() === SPOT_NATIVE;
  const dir = /\/mainnet\/([^/]+)\/(logo\.[a-z]+)$/.exec(t.logoURI ?? "");
  return {
    symbol: t.symbol,
    name: t.name,
    address: native ? SPOT_NATIVE : getAddress(t.address),
    decimals: t.decimals,
    native,
    mark: native ? `native:${MAINNET_CHAIN_ID}:MON` : `token:${MAINNET_CHAIN_ID}:${t.address.toLowerCase()}`,
    list: { dir: decodeURIComponent(dir?.[1] ?? t.symbol), logo: dir?.[2] ?? "logo.svg" },
    ...(t.extensions?.coinGeckoId ? { coingeckoId: t.extensions.coinGeckoId } : {}),
    quote,
    pool: own,
    route,
    impactBps: 0,
  };
}

/** The best route (max output for the reference buy) among the candidates, with its impact; undefined if none quote. */
async function bestRoute(t: ListToken, options: Array<{ quote: SpotQuote; own: SpotPool; route: SpotPool[] }>) {
  let best: { token: SpotToken; out: bigint } | undefined;
  for (const o of options) {
    const token = provisional(t, o.quote, o.own, o.route);
    try {
      const q = await quoteSpot(read, token, "buy", refUsdc);
      const { feeBps, priceImpactBps: impactBps } = q;
      console.log(
        `    ${o.quote} fee ${o.own.key.fee} ts ${o.own.key.tickSpacing} hops ${o.route.length}: fees ${feeBps} bps impact ${impactBps} bps`,
      );
      if (!best || q.amountOut > best.out)
        best = { token: { ...token, impactBps: Number(impactBps) }, out: q.amountOut };
    } catch (error) {
      console.log(
        `    ${o.quote} ${o.own.poolId.slice(0, 10)}: quote failed (${(error as Error).message.split("\n")[0]})`,
      );
    }
  }
  return best?.token;
}

async function main(): Promise<void> {
  const listUrl = `${MONAD_TOKEN_LIST.raw}/${MONAD_TOKEN_LIST.commit}/${MONAD_TOKEN_LIST.mainnetFile}`;
  const list = (await (await fetch(listUrl)).json()) as {
    version: { major: number; minor: number; patch: number };
    tokens: ListToken[];
  };
  const version = `${list.version.major}.${list.version.minor}.${list.version.patch}`;
  const all = list.tokens.filter((t) => t.chainId === MAINNET_CHAIN_ID);
  console.log(
    `token list ${version} @ ${MONAD_TOKEN_LIST.commit.slice(0, SHORT_SHA_CHARS)}: ${all.length} mainnet tokens`,
  );
  const candidates: ListToken[] = [];
  for (const t of all) {
    const a = t.address.toLowerCase();
    if (a === usdc.toLowerCase() || a === ausd.toLowerCase())
      drop(t, "quote currency (the collateral pair; swapped by F26)");
    else if (a === WMON) drop(t, "wrapped MON (native MON is listed)");
    else candidates.push(t);
  }

  // GeckoTerminal: total reserves per token, then the v4 pools of every token with enough of them.
  const reserves = new Map<string, number>();
  for (let i = 0; i < candidates.length; i += GT_MULTI_MAX) {
    const chunk = candidates.slice(i, i + GT_MULTI_MAX).map((t) => t.address.toLowerCase());
    const res = await gt<{ data: Array<{ attributes: { address: string; total_reserve_in_usd: string } }> }>(
      `/tokens/multi/${chunk.join(",")}`,
    );
    for (const d of res.data)
      reserves.set(d.attributes.address.toLowerCase(), Number(d.attributes.total_reserve_in_usd));
  }
  const discovered = new Map<string, Array<{ id: Hex; quote: SpotQuote; reserveUsd: number }>>();
  for (const t of candidates) {
    const reserve = reserves.get(t.address.toLowerCase());
    if (reserve === undefined) {
      drop(t, "not indexed by GeckoTerminal on Monad (no DEX pool)");
      continue;
    }
    if (reserve < MIN_TOKEN_RESERVE_USD) {
      drop(t, `$${Math.round(reserve)} in Monad DEX reserves (< $${MIN_TOKEN_RESERVE_USD})`);
      continue;
    }
    const res = await gt<{ data: GtPool[] }>(`/tokens/${t.address.toLowerCase()}/pools?page=1`);
    const self = t.address.toLowerCase();
    const pools = res.data
      .filter((p) => p.relationships.dex.data.id === GECKOTERMINAL_UNISWAP_V4)
      .map((p) => {
        const [base, quote] = [p.relationships.base_token, p.relationships.quote_token].map((r) =>
          r.data.id.replace(`${GECKOTERMINAL_NETWORK}_`, "").toLowerCase(),
        );
        const other = base === self ? quote : base;
        return {
          id: p.attributes.address as Hex,
          quote: QUOTES[other ?? ""],
          reserveUsd: Number(p.attributes.reserve_in_usd),
        };
      })
      .filter((p): p is { id: Hex; quote: SpotQuote; reserveUsd: number } => p.quote !== undefined)
      .filter((p) => !(self === SPOT_NATIVE && p.quote === "MON"));
    if (pools.length === 0) drop(t, "no Uniswap v4 pool against USDC, AUSD or MON");
    else discovered.set(self, pools);
  }

  // Keys and live state, onchain.
  const ids = [...discovered.values()].flat().map((p) => p.id);
  const keys = await keysOf(ids);
  const states = new Map(
    (await readPoolStates(read, [...keys.values()])).map((s) => [s.poolId.toLowerCase(), s] as const),
  );
  const stable = await findStablePool(read);
  if (!stable) throw new Error("no AUSD/USDC stable pool — the AUSD bridge is missing");
  const ausdBridge = pool(stable.key);
  /** Live hook-free pools of a token, and why the others can't be used. */
  const usable = (self: string) => {
    const out: Array<{ quote: SpotQuote; own: SpotPool }> = [];
    const why: string[] = [];
    for (const p of discovered.get(self) ?? []) {
      const key = keys.get(p.id.toLowerCase());
      const state = states.get(p.id.toLowerCase());
      const tag = `${p.quote} ${p.id.slice(0, POOL_TAG_CHARS)}`;
      if (!key) why.push(`${tag} not known to the PositionManager`);
      else if (key.hooks !== zeroAddress) why.push(`${tag} hooked (${key.hooks})`);
      else if (!state || !isLive(state)) why.push(`${tag} no liquidity in range`);
      else out.push({ quote: p.quote, own: pool(key) });
    }
    return { out, why };
  };

  // MON first: its route is every MON-quoted token's bridge.
  const byAddress = new Map(candidates.map((t) => [t.address.toLowerCase(), t]));
  const monListed = byAddress.get(SPOT_NATIVE);
  if (!monListed) throw new Error("MON is missing from the token list");
  console.log("MON");
  const monOptions = usable(SPOT_NATIVE).out.map((o) => ({
    ...o,
    route: o.quote === "AUSD" ? [ausdBridge, o.own] : [o.own],
  }));
  const mon = await bestRoute(monListed, monOptions);
  if (!mon) throw new Error("no live MON route from USDC");

  const listed: SpotToken[] = [mon];
  for (const [self, t] of byAddress) {
    if (self === SPOT_NATIVE || !discovered.has(self)) continue;
    console.log(t.symbol);
    const { out, why } = usable(self);
    const options = out.map((o) => ({
      ...o,
      route: o.quote === "USDC" ? [o.own] : o.quote === "AUSD" ? [ausdBridge, o.own] : [...mon.route, o.own],
    }));
    if (options.length === 0) {
      drop(t, `no usable v4 pool: ${why.join("; ")}`);
      continue;
    }
    const best = await bestRoute(t, options);
    if (!best) drop(t, "no route quoted");
    else if (BigInt(best.impactBps) > MAX_LISTING_IMPACT_BPS)
      drop(t, `a $${SPOT_REFERENCE_USD} buy moves its best route ${best.impactBps} bps beyond fees`);
    else listed.push(best);
  }

  // The list's decimals must be the token's own.
  const erc20s = listed.filter((t) => !t.native);
  const decimals = await read.multicall({
    contracts: erc20s.map((t) => ({ address: t.address, abi: erc20Abi, functionName: "decimals" }) as const),
    allowFailure: false,
  });
  const wrong = new Set(erc20s.filter((t, i) => decimals[i] !== t.decimals).map((t) => t.address));
  for (const t of listed.filter((x) => wrong.has(x.address)))
    drop(byAddress.get(t.address.toLowerCase()) as ListToken, "list decimals ≠ onchain decimals()");
  const tokens = listed.filter((t) => !wrong.has(t.address));

  const meta = {
    list: listUrl,
    listVersion: version,
    generated: new Date().toISOString().slice(0, ISO_DATE_CHARS),
    referenceUsd: SPOT_REFERENCE_USD,
    maxImpactBps: Number(MAX_LISTING_IMPACT_BPS),
    discovery: `GeckoTerminal ${GECKOTERMINAL_UNISWAP_V4} pools → PositionManager.poolKeys → StateView`,
  };
  mkdirSync(dirname(OUT), { recursive: true });
  const body = [
    HEADER,
    'import type { SpotToken } from "../spot.ts";',
    "",
    `export const SPOT_TOKENS_SOURCE = ${JSON.stringify(meta, null, JSON_INDENT)} as const;`,
    "",
    `export const SPOT_TOKENS: readonly SpotToken[] = ${JSON.stringify(tokens, null, JSON_INDENT)};`,
    "",
  ].join("\n");
  writeFileSync(OUT, body);
  writeFileSync(DROPPED, `${JSON.stringify({ ...meta, dropped }, null, JSON_INDENT)}\n`);
  console.log(`\n${tokens.length} listed: ${tokens.map((t) => `${t.symbol}/${t.quote}`).join(" ")}`);
  console.log(`${dropped.length} dropped → ${DROPPED.slice(ROOT.length + 1)}`);
}

await main();
