#!/usr/bin/env node
/**
 * contracts-export — Foundry artifacts → `@senryo/contracts` (typed ABIs `as const` + addresses).
 *
 *   pnpm contracts:export            (runs `forge build` first unless --no-build)
 *
 * Writes:
 *  - packages/contracts/src/abis/<camelName>Abi.ts   one `as const` ABI per exported contract
 *  - packages/contracts/src/abis/index.ts            re-exports
 *  - packages/contracts/src/addresses/index.ts       typed view of addresses/<chainId>.json (written by
 *                                                    contracts/script/Deploy.s.sol); JSON files are validated here
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "contracts/out");
const PKG = join(ROOT, "packages/contracts/src");
const ABI_DIR = join(PKG, "abis");
const ADDR_DIR = join(PKG, "addresses");
const HEADER = "// Generated by scripts/contracts-export.mjs — do not edit.\n";
const ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/;
const HASH_RE = /^0x[0-9a-fA-F]{64}$/;

/** [artifact file, contract name] for every contract a client, service or the indexer talks to. */
const CONTRACTS = [
  ["BandReserve.sol", "BandReserve"],
  ["DuelArena.sol", "DuelArena"],
  ["Windows.sol", "Windows"],
  ["PythPrintVerifier.sol", "PythPrintVerifier"],
  ["BasketPrintVerifier.sol", "BasketPrintVerifier"],
  ["PoolShares.sol", "PoolShares"],
  ["RedStonePrintVerifier.sol", "RedStonePrintVerifier"],
  ["RedStoneBasketVerifier.sol", "RedStoneBasketVerifier"],
  ["TestUSD.sol", "TestUSD"],
  ["MarketCalendar.sol", "MarketCalendar"],
  ["AccessManager.sol", "AccessManager"],
];

function camel(name) {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function exportAbis() {
  mkdirSync(ABI_DIR, { recursive: true });
  const index = [];
  for (const [file, name] of CONTRACTS) {
    const artifact = join(OUT, file, `${name}.json`);
    if (!existsSync(artifact)) throw new Error(`missing artifact ${artifact} — run forge build`);
    const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
    const constName = `${camel(name)}Abi`;
    const body = `${HEADER}export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
    writeFileSync(join(ABI_DIR, `${constName}.ts`), body);
    index.push(`export { ${constName} } from "./${constName}";`);
  }
  writeFileSync(join(ABI_DIR, "index.ts"), `${HEADER}${index.join("\n")}\n`);
  return CONTRACTS.length;
}

function validateBook(file, book) {
  if (!Number.isInteger(book.chainId)) throw new Error(`${file}: chainId must be an integer`);
  for (const [name, entry] of Object.entries(book.contracts ?? {})) {
    if (!ADDRESS_RE.test(entry.address)) throw new Error(`${file}: ${name}.address invalid`);
    if (!HASH_RE.test(entry.initCodeHash)) throw new Error(`${file}: ${name}.initCodeHash invalid`);
    if (!Number.isInteger(entry.startBlock)) throw new Error(`${file}: ${name}.startBlock invalid`);
    if (typeof entry.indexed !== "boolean") throw new Error(`${file}: ${name}.indexed invalid`);
  }
}

function exportAddresses() {
  mkdirSync(ADDR_DIR, { recursive: true });
  const files = readdirSync(ADDR_DIR).filter((f) => /^\d+\.json$/.test(f));
  const imports = [];
  const entries = [];
  for (const file of files) {
    const book = JSON.parse(readFileSync(join(ADDR_DIR, file), "utf8"));
    validateBook(file, book);
    // Normalise what forge's vm.writeJson produced so the committed file is stable and Biome-formatted.
    writeFileSync(join(ADDR_DIR, file), `${JSON.stringify(book, null, 2)}\n`);
    const id = file.replace(".json", "");
    imports.push(`import book${id} from "./${file}";`);
    entries.push(`  ${id}: book${id} as AddressBook,`);
  }
  const body = `${HEADER}${imports.join("\n")}${imports.length ? "\n\n" : ""}export type ContractEntry = {
  readonly address: \`0x\${string}\`;
  readonly initCodeHash: \`0x\${string}\`;
  readonly startBlock: number;
  readonly indexed: boolean;
};

export type AddressBook = {
  readonly chainId: number;
  readonly contracts: Readonly<Record<string, ContractEntry>>;
};

/** Deployed contracts per chain id (143 mainnet, 10143 testnet); empty until Deploy.s.sol has run. */
export const addressBooks: Readonly<Record<number, AddressBook>> = ${entries.length ? `{\n${entries.join("\n")}\n}` : "{}"};
`;
  writeFileSync(join(ADDR_DIR, "index.ts"), body);
  return files.length;
}

if (!process.argv.includes("--no-build")) {
  execFileSync("forge", ["build"], { cwd: join(ROOT, "contracts"), stdio: "inherit" });
}
const abis = exportAbis();
const books = exportAddresses();
console.log(`contracts-export: ${abis} ABIs, ${books} address book(s) → packages/contracts/src`);
