/**
 * RedStone's signed feeds (D-284): the stocks our Pyth key can't stream and more coins, each named by its RedStone
 * data-feed id (`redstone-primary-prod`, checked live 9 Oct 2026: five signers on a 10-second grid). Stocks trade on the
 * US calendar (the regular feed holds its last value outside it). PEPE and SHIB are left out: signed to three
 * significant figures, a 1-minute window would tie too often. σ measured like the Pyth markets (×1.5).
 */
import { CADENCES_SEC } from "../cadences.ts";
import type { MarketSpec } from "../catalog.ts";
import { MAINNET_CHAIN_ID, TESTNET_CHAIN_ID } from "../networks.ts";

export const REDSTONE_MARKETS: readonly MarketSpec[] = [
  {
    symbol: "NVDA",
    name: "Nvidia",
    kind: "equity",
    source: { kind: "redstone", feed: "NVDA" },
    annualVol: 0.65,
    cadences: CADENCES_SEC,
    calendarId: 1,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "AAPL",
    name: "Apple",
    kind: "equity",
    source: { kind: "redstone", feed: "AAPL" },
    annualVol: 0.64,
    cadences: CADENCES_SEC,
    calendarId: 1,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    kind: "equity",
    source: { kind: "redstone", feed: "MSFT" },
    annualVol: 0.71,
    cadences: CADENCES_SEC,
    calendarId: 1,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "META",
    name: "Meta",
    kind: "equity",
    source: { kind: "redstone", feed: "META" },
    annualVol: 0.77,
    cadences: CADENCES_SEC,
    calendarId: 1,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "GOOGL",
    name: "Alphabet",
    kind: "equity",
    source: { kind: "redstone", feed: "GOOGL" },
    annualVol: 0.7,
    cadences: CADENCES_SEC,
    calendarId: 1,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "AMZN",
    name: "Amazon",
    kind: "equity",
    source: { kind: "redstone", feed: "AMZN" },
    annualVol: 0.69,
    cadences: CADENCES_SEC,
    calendarId: 1,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "PLTR",
    name: "Palantir",
    kind: "equity",
    source: { kind: "redstone", feed: "PLTR" },
    annualVol: 1.5,
    cadences: CADENCES_SEC,
    calendarId: 1,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "AMD",
    name: "AMD",
    kind: "equity",
    source: { kind: "redstone", feed: "AMD" },
    annualVol: 1.27,
    cadences: CADENCES_SEC,
    calendarId: 1,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "AVAX",
    name: "Avalanche",
    kind: "crypto",
    source: { kind: "redstone", feed: "AVAX" },
    annualVol: 1.3,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "LINK",
    name: "Chainlink",
    kind: "crypto",
    source: { kind: "redstone", feed: "LINK" },
    annualVol: 0.97,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "SUI",
    name: "Sui",
    kind: "crypto",
    source: { kind: "redstone", feed: "SUI" },
    annualVol: 1.35,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "TON",
    name: "Toncoin",
    kind: "crypto",
    source: { kind: "redstone", feed: "TON" },
    annualVol: 1.22,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "ADA",
    name: "Cardano",
    kind: "crypto",
    source: { kind: "redstone", feed: "ADA" },
    annualVol: 1.39,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "LTC",
    name: "Litecoin",
    kind: "crypto",
    source: { kind: "redstone", feed: "LTC" },
    annualVol: 0.87,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "DOT",
    name: "Polkadot",
    kind: "crypto",
    source: { kind: "redstone", feed: "DOT" },
    annualVol: 1.54,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "NEAR",
    name: "NEAR",
    kind: "crypto",
    source: { kind: "redstone", feed: "NEAR" },
    annualVol: 2.2,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "AAVE",
    name: "Aave",
    kind: "crypto",
    source: { kind: "redstone", feed: "AAVE" },
    annualVol: 1.25,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
  {
    symbol: "UNI",
    name: "Uniswap",
    kind: "crypto",
    source: { kind: "redstone", feed: "UNI" },
    annualVol: 1.36,
    cadences: CADENCES_SEC,
    calendarId: 0,
    chains: [TESTNET_CHAIN_ID, MAINNET_CHAIN_ID],
  },
];
