// Generated by scripts/contracts-export.mjs — do not edit.
export const basketPrintVerifierAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "pyth_",
        "type": "address",
        "internalType": "contract IPyth"
      },
      {
        "name": "graceSec_",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "maxConfBps_",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "admissionSec_",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "MAX_ADMISSION_SEC",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_GRACE_SEC",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "admissionSec",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "basketId",
    "inputs": [
      {
        "name": "def",
        "type": "tuple",
        "internalType": "struct BasketPrintVerifier.Basket",
        "components": [
          {
            "name": "ids",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "weightsBps",
            "type": "uint16[]",
            "internalType": "uint16[]"
          },
          {
            "name": "basesE8",
            "type": "int64[]",
            "internalType": "int64[]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "fee",
    "inputs": [
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "graceSec",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxConfBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "normalize",
    "inputs": [
      {
        "name": "price",
        "type": "int256",
        "internalType": "int256"
      },
      {
        "name": "expo",
        "type": "int32",
        "internalType": "int32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "int64",
        "internalType": "int64"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "normalizeUnsigned",
    "inputs": [
      {
        "name": "conf",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expo",
        "type": "int32",
        "internalType": "int32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "pyth",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPyth"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verifyPrint",
    "inputs": [
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "feedId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "priceE8",
        "type": "int64",
        "internalType": "int64"
      },
      {
        "name": "confE8",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "publishTime",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "event",
    "name": "BasketPrint",
    "inputs": [
      {
        "name": "basketId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "indexed": true,
        "internalType": "uint40"
      },
      {
        "name": "pricesE8",
        "type": "int64[]",
        "indexed": false,
        "internalType": "int64[]"
      },
      {
        "name": "confsE8",
        "type": "uint64[]",
        "indexed": false,
        "internalType": "uint64[]"
      },
      {
        "name": "times",
        "type": "uint40[]",
        "indexed": false,
        "internalType": "uint40[]"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadBasket",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPrice",
    "inputs": [
      {
        "name": "price",
        "type": "int256",
        "internalType": "int256"
      },
      {
        "name": "expo",
        "type": "int32",
        "internalType": "int32"
      }
    ]
  },
  {
    "type": "error",
    "name": "LowQuality",
    "inputs": [
      {
        "name": "price",
        "type": "int64",
        "internalType": "int64"
      },
      {
        "name": "conf",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotUnique",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "internalType": "uint40"
      }
    ]
  },
  {
    "type": "error",
    "name": "OutOfWindow",
    "inputs": [
      {
        "name": "publishTime",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "t",
        "type": "uint40",
        "internalType": "uint40"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongBasket",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "defined",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongFee",
    "inputs": [
      {
        "name": "sent",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
