// Generated by scripts/contracts-export.mjs — do not edit.
export const pythBoundaryOracleAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "receiver_",
        "type": "address",
        "internalType": "contract IPythBoundary"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "PYTH_TESTNET",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "fee",
    "inputs": [
      {
        "name": "proof",
        "type": "bytes[]",
        "internalType": "bytes[]"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "receiver",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPythBoundary"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verify",
    "inputs": [
      {
        "name": "feed",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "boundary",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "proof",
        "type": "bytes[]",
        "internalType": "bytes[]"
      }
    ],
    "outputs": [
      {
        "name": "o",
        "type": "tuple",
        "internalType": "struct PythBoundaryOracle.Observation",
        "components": [
          {
            "name": "price",
            "type": "int64",
            "internalType": "int64"
          },
          {
            "name": "confidence",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "exponent",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "publishTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "proofHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "quality",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "error",
    "name": "InvalidProof",
    "inputs": []
  }
] as const;
