// Generated by scripts/contracts-export.mjs — do not edit.
export const redStoneBasketVerifierAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "single_",
        "type": "address",
        "internalType": "contract RedStonePrintVerifier"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "admissionSec",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "basketId",
    "inputs": [
      {
        "name": "def",
        "type": "tuple",
        "internalType": "struct RedStoneBasketVerifier.Basket",
        "components": [
          {
            "name": "ids",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          },
          {
            "name": "weightsBps",
            "type": "uint16[]",
            "internalType": "uint16[]"
          },
          {
            "name": "basesE8",
            "type": "int64[]",
            "internalType": "int64[]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "fee",
    "inputs": [
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "single",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract RedStonePrintVerifier"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verifyPrint",
    "inputs": [
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "feedId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "priceE8",
        "type": "int64",
        "internalType": "int64"
      },
      {
        "name": "confE8",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "publishTime",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "event",
    "name": "BasketPrint",
    "inputs": [
      {
        "name": "basketId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "indexed": true,
        "internalType": "uint40"
      },
      {
        "name": "pricesE8",
        "type": "int64[]",
        "indexed": false,
        "internalType": "int64[]"
      },
      {
        "name": "confsE8",
        "type": "uint64[]",
        "indexed": false,
        "internalType": "uint64[]"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadBasket",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeNotTaken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongBasket",
    "inputs": [
      {
        "name": "feedId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "defined",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  }
] as const;
