// Generated by scripts/contracts-export.mjs — do not edit.
export const sessionOracleAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "authority",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "calendar_",
        "type": "address",
        "internalType": "contract IMarketCalendar"
      },
      {
        "name": "inits",
        "type": "tuple[]",
        "internalType": "struct SessionOracle.FeedInit[]",
        "components": [
          {
            "name": "marketId",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "feed",
            "type": "address",
            "internalType": "contract AggregatorV3Interface"
          },
          {
            "name": "descriptionHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "calendarId",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "heartbeat",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "clampBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "reopenClampBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "acceptFeedPrice",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "allOpen",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "authority",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "calendar",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IMarketCalendar"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeds",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "feed",
        "type": "address",
        "internalType": "contract AggregatorV3Interface"
      },
      {
        "name": "calendarId",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "decimals",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "heartbeat",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "clampBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "reopenClampBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "halt",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isConsumingScheduledOp",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "marketCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "marketIds",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "observe",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PriceView",
        "components": [
          {
            "name": "price18",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "latest18",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum MarketStatus"
          },
          {
            "name": "spreadBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "peek",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PriceView",
        "components": [
          {
            "name": "price18",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "latest18",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum MarketStatus"
          },
          {
            "name": "spreadBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setAuthority",
    "inputs": [
      {
        "name": "newAuthority",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeed",
    "inputs": [
      {
        "name": "init",
        "type": "tuple",
        "internalType": "struct SessionOracle.FeedInit",
        "components": [
          {
            "name": "marketId",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "feed",
            "type": "address",
            "internalType": "contract AggregatorV3Interface"
          },
          {
            "name": "descriptionHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "calendarId",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "heartbeat",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "clampBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "reopenClampBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "states",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "lastPrice18",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "lastUpdatedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "haltedUntil",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "lastRoundId",
        "type": "uint80",
        "internalType": "uint80"
      },
      {
        "name": "circuit",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "closedSeen",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "lastStatus",
        "type": "uint8",
        "internalType": "enum MarketStatus"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unhalt",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AuthorityUpdated",
    "inputs": [
      {
        "name": "authority",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeedSet",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "feed",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "calendarId",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "clampBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "reopenClampBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarketHalted",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "until",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarketStatusChanged",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "previous",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum MarketStatus"
      },
      {
        "name": "current",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum MarketStatus"
      },
      {
        "name": "price18",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PriceAccepted",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint80",
        "indexed": false,
        "internalType": "uint80"
      },
      {
        "name": "price18",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "updatedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PriceRejected",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint80",
        "indexed": false,
        "internalType": "uint80"
      },
      {
        "name": "answer18",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "lastAccepted18",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AccessManagedInvalidAuthority",
    "inputs": [
      {
        "name": "authority",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "AccessManagedRequiredDelay",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "delay",
        "type": "uint32",
        "internalType": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AccessManagedUnauthorized",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "DescriptionMismatch",
    "inputs": [
      {
        "name": "expected",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "actual",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "FeedAnswerInvalid",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeedDecimalsUnsupported",
    "inputs": [
      {
        "name": "decimals",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownMarket",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
