// Generated by scripts/contracts-export.mjs — do not edit.
export const windowsAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "authority",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "calendar_",
        "type": "address",
        "internalType": "contract IMarketCalendar"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addPolicyVersion",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "index",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "v",
        "type": "tuple",
        "internalType": "struct PolicyVersion",
        "components": [
          {
            "name": "validFrom",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "validUntil",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "maxDivergenceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "primary",
            "type": "tuple",
            "internalType": "struct PrintSource",
            "components": [
              {
                "name": "verifier",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "feedId",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "check",
            "type": "tuple",
            "internalType": "struct PrintSource",
            "components": [
              {
                "name": "verifier",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "feedId",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "authority",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "calendar",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IMarketCalendar"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "diverges",
    "inputs": [
      {
        "name": "primary",
        "type": "int64",
        "internalType": "int64"
      },
      {
        "name": "check",
        "type": "int64",
        "internalType": "int64"
      },
      {
        "name": "bps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "ensurePrint",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feedId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "internalType": "uint40"
      },
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct Print",
        "components": [
          {
            "name": "priceE8",
            "type": "int64",
            "internalType": "int64"
          },
          {
            "name": "confE8",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "publishTime",
            "type": "uint40",
            "internalType": "uint40"
          }
        ]
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "isConsumingScheduledOp",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "knownVerifier",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "openPrintOf",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Print",
        "components": [
          {
            "name": "priceE8",
            "type": "int64",
            "internalType": "int64"
          },
          {
            "name": "confE8",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "publishTime",
            "type": "uint40",
            "internalType": "uint40"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "openWindow",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "start",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "policyOf",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "index",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PolicyVersion",
        "components": [
          {
            "name": "validFrom",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "validUntil",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "maxDivergenceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "primary",
            "type": "tuple",
            "internalType": "struct PrintSource",
            "components": [
              {
                "name": "verifier",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "feedId",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "check",
            "type": "tuple",
            "internalType": "struct PrintSource",
            "components": [
              {
                "name": "verifier",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "feedId",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "primarySourceOf",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PrintSource",
        "components": [
          {
            "name": "verifier",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "feedId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "printKeyOf",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feedId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "printOf",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feedId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Print",
        "components": [
          {
            "name": "priceE8",
            "type": "int64",
            "internalType": "int64"
          },
          {
            "name": "confE8",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "publishTime",
            "type": "uint40",
            "internalType": "uint40"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "recordPrint",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feedId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "internalType": "uint40"
      },
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Print",
        "components": [
          {
            "name": "priceE8",
            "type": "int64",
            "internalType": "int64"
          },
          {
            "name": "confE8",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "publishTime",
            "type": "uint40",
            "internalType": "uint40"
          }
        ]
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "registerSeries",
    "inputs": [
      {
        "name": "market",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "cadenceSec",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "calendarId",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "v0",
        "type": "tuple",
        "internalType": "struct PolicyVersion",
        "components": [
          {
            "name": "validFrom",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "validUntil",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "maxDivergenceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "primary",
            "type": "tuple",
            "internalType": "struct PrintSource",
            "components": [
              {
                "name": "verifier",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "feedId",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "check",
            "type": "tuple",
            "internalType": "struct PrintSource",
            "components": [
              {
                "name": "verifier",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "feedId",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "resolve",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "seriesIdOf",
    "inputs": [
      {
        "name": "market",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "cadenceSec",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "seriesOf",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Series",
        "components": [
          {
            "name": "market",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "cadenceSec",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "calendarId",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "versionCount",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setAuthority",
    "inputs": [
      {
        "name": "newAuthority",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "voidExpired",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "windowIdOf",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "start",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "windowOf",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Window",
        "components": [
          {
            "name": "seriesId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "start",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "expiry",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "policyVersion",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "state",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "voidReason",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "openE8",
            "type": "int64",
            "internalType": "int64"
          },
          {
            "name": "closeE8",
            "type": "int64",
            "internalType": "int64"
          },
          {
            "name": "resolvedAt",
            "type": "uint40",
            "internalType": "uint40"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AuthorityUpdated",
    "inputs": [
      {
        "name": "authority",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PolicyVersionAdded",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "index",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "validFrom",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      },
      {
        "name": "validUntil",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      },
      {
        "name": "primaryVerifier",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "primaryFeed",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "checkVerifier",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "checkFeed",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "maxDivergenceBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PrintRecorded",
    "inputs": [
      {
        "name": "printKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "verifier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "feedId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "t",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      },
      {
        "name": "priceE8",
        "type": "int64",
        "indexed": false,
        "internalType": "int64"
      },
      {
        "name": "confE8",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "publishTime",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      },
      {
        "name": "by",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SeriesRegistered",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "market",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "cadenceSec",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "calendarId",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WindowOpened",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "seriesId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "start",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      },
      {
        "name": "expiry",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      },
      {
        "name": "policyVersion",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "by",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WindowResolved",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "state",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "voidReason",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "openE8",
        "type": "int64",
        "indexed": false,
        "internalType": "int64"
      },
      {
        "name": "closeE8",
        "type": "int64",
        "indexed": false,
        "internalType": "int64"
      },
      {
        "name": "by",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AccessManagedInvalidAuthority",
    "inputs": [
      {
        "name": "authority",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "AccessManagedRequiredDelay",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "delay",
        "type": "uint32",
        "internalType": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AccessManagedUnauthorized",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadAlignment",
    "inputs": [
      {
        "name": "start",
        "type": "uint40",
        "internalType": "uint40"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadCadence",
    "inputs": [
      {
        "name": "cadenceSec",
        "type": "uint32",
        "internalType": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadHorizon",
    "inputs": [
      {
        "name": "start",
        "type": "uint40",
        "internalType": "uint40"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadPolicy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CrossCheckPending",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "MarketClosed",
    "inputs": [
      {
        "name": "calendarId",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "at",
        "type": "uint40",
        "internalType": "uint40"
      }
    ]
  },
  {
    "type": "error",
    "name": "PolicyVersionImmutable",
    "inputs": [
      {
        "name": "index",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "PrintAlreadyRecorded",
    "inputs": [
      {
        "name": "printKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "PrintTooLate",
    "inputs": [
      {
        "name": "t",
        "type": "uint40",
        "internalType": "uint40"
      },
      {
        "name": "deadline",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "PrintsMissing",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SeriesExists",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SettlementWindowOpen",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SourceNotCovered",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "start",
        "type": "uint40",
        "internalType": "uint40"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownPolicyVersion",
    "inputs": [
      {
        "name": "index",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownSeries",
    "inputs": [
      {
        "name": "seriesId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownVerifier",
    "inputs": [
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownWindow",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "WindowExists",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "WindowTerminal",
    "inputs": [
      {
        "name": "windowId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  }
] as const;
